// This file is auto-generated by @hey-api/openapi-ts

import type {
	AddIntegrationResponse,
	AddSandboxByYamlResponse,
	AddSandboxResponse,
	AddSandboxSnapshotResponse,
	CreateSandboxDirectoryResponse,
	GetIntegrationResponse,
	GetIntegrationsResponse,
	GetProjectSnapshotsResponse,
	GetSandboxContentResponse,
	GetSandboxResponse,
	GetSandboxSnapshotResponse,
	GetSandboxSnapshotsResponse,
	GetWorkspaceMemberProjectsResponse,
	GetWorkspaceResponse,
	RestartSandboxResponse,
	StartSandboxResponse,
	StopSandboxResponse,
	UpdateIntegrationResponse,
	UpdateSandboxByYamlResponse,
	UpdateSandboxResponse,
	UploadSandboxFileResponse,
} from "./types.gen";

const workspaceViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

export const getWorkspaceResponseTransformer = async (
	data: any,
): Promise<GetWorkspaceResponse> => {
	data = workspaceViewSchemaResponseTransformer(data);
	return data;
};

const pipelineEventViewSchemaResponseTransformer = (data: any) => {
	if (data.start_date) {
		data.start_date = new Date(data.start_date);
	}
	if (data.delay) {
		data.delay = BigInt(data.delay.toString());
	}
	return data;
};

const shortPipelineViewSchemaResponseTransformer = (data: any) => {
	if (data.events) {
		data.events = data.events.map((item: any) =>
			pipelineEventViewSchemaResponseTransformer(item),
		);
	}
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const integrationViewSchemaResponseTransformer = (data: any) => {
	if (data.allowed_pipelines) {
		data.allowed_pipelines = data.allowed_pipelines.map((item: any) =>
			shortPipelineViewSchemaResponseTransformer(item),
		);
	}
	return data;
};

const integrationsViewSchemaResponseTransformer = (data: any) => {
	if (data.integrations) {
		data.integrations = data.integrations.map((item: any) =>
			integrationViewSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getIntegrationsResponseTransformer = async (
	data: any,
): Promise<GetIntegrationsResponse> => {
	data = integrationsViewSchemaResponseTransformer(data);
	return data;
};

export const addIntegrationResponseTransformer = async (
	data: any,
): Promise<AddIntegrationResponse> => {
	data = integrationViewSchemaResponseTransformer(data);
	return data;
};

export const getIntegrationResponseTransformer = async (
	data: any,
): Promise<GetIntegrationResponse> => {
	data = integrationViewSchemaResponseTransformer(data);
	return data;
};

export const updateIntegrationResponseTransformer = async (
	data: any,
): Promise<UpdateIntegrationResponse> => {
	data = integrationViewSchemaResponseTransformer(data);
	return data;
};

const shortProjectViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const projectsViewSchemaResponseTransformer = (data: any) => {
	if (data.projects) {
		data.projects = data.projects.map((item: any) =>
			shortProjectViewSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getWorkspaceMemberProjectsResponseTransformer = async (
	data: any,
): Promise<GetWorkspaceMemberProjectsResponse> => {
	data = projectsViewSchemaResponseTransformer(data);
	return data;
};

const projectViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const sandboxResponseSchemaResponseTransformer = (data: any) => {
	if (data.project) {
		data.project = projectViewSchemaResponseTransformer(data.project);
	}
	return data;
};

export const addSandboxResponseTransformer = async (
	data: any,
): Promise<AddSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const getSandboxResponseTransformer = async (
	data: any,
): Promise<GetSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const updateSandboxResponseTransformer = async (
	data: any,
): Promise<UpdateSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

const sandboxContentItemSchemaResponseTransformer = (data: any) => {
	if (data.size) {
		data.size = BigInt(data.size.toString());
	}
	return data;
};

const sandboxContentViewSchemaResponseTransformer = (data: any) => {
	if (data.contents) {
		data.contents = data.contents.map((item: any) =>
			sandboxContentItemSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getSandboxContentResponseTransformer = async (
	data: any,
): Promise<GetSandboxContentResponse> => {
	data = sandboxContentViewSchemaResponseTransformer(data);
	return data;
};

export const createSandboxDirectoryResponseTransformer = async (
	data: any,
): Promise<CreateSandboxDirectoryResponse> => {
	data = sandboxContentItemSchemaResponseTransformer(data);
	return data;
};

export const uploadSandboxFileResponseTransformer = async (
	data: any,
): Promise<UploadSandboxFileResponse> => {
	data = sandboxContentItemSchemaResponseTransformer(data);
	return data;
};

export const restartSandboxResponseTransformer = async (
	data: any,
): Promise<RestartSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

const shortSnapshotViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const snapshotsViewSchemaResponseTransformer = (data: any) => {
	if (data.snapshots) {
		data.snapshots = data.snapshots.map((item: any) =>
			shortSnapshotViewSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getSandboxSnapshotsResponseTransformer = async (
	data: any,
): Promise<GetSandboxSnapshotsResponse> => {
	data = snapshotsViewSchemaResponseTransformer(data);
	return data;
};

const snapshotViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

export const addSandboxSnapshotResponseTransformer = async (
	data: any,
): Promise<AddSandboxSnapshotResponse> => {
	data = snapshotViewSchemaResponseTransformer(data);
	return data;
};

export const getSandboxSnapshotResponseTransformer = async (
	data: any,
): Promise<GetSandboxSnapshotResponse> => {
	data = snapshotViewSchemaResponseTransformer(data);
	return data;
};

export const startSandboxResponseTransformer = async (
	data: any,
): Promise<StartSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const stopSandboxResponseTransformer = async (
	data: any,
): Promise<StopSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const updateSandboxByYamlResponseTransformer = async (
	data: any,
): Promise<UpdateSandboxByYamlResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const getProjectSnapshotsResponseTransformer = async (
	data: any,
): Promise<GetProjectSnapshotsResponse> => {
	data = snapshotsViewSchemaResponseTransformer(data);
	return data;
};

export const addSandboxByYamlResponseTransformer = async (
	data: any,
): Promise<AddSandboxByYamlResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};
