// This file is auto-generated by @hey-api/openapi-ts

import type {
	AddSandboxByYamlResponse,
	AddSandboxResponse,
	AddSandboxSnapshotResponse,
	CreateSandboxDirectoryResponse,
	GetProjectSnapshotsResponse,
	GetSandboxContentResponse,
	GetSandboxResponse,
	GetSandboxSnapshotResponse,
	GetSandboxSnapshotsResponse,
	RestartSandboxResponse,
	StartSandboxResponse,
	StopSandboxResponse,
	UpdateSandboxByYamlResponse,
	UpdateSandboxResponse,
	UploadSandboxFileResponse,
} from "./types.gen";

const projectViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const sandboxResponseSchemaResponseTransformer = (data: any) => {
	if (data.project) {
		data.project = projectViewSchemaResponseTransformer(data.project);
	}
	return data;
};

export const addSandboxResponseTransformer = async (
	data: any,
): Promise<AddSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const getSandboxResponseTransformer = async (
	data: any,
): Promise<GetSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const updateSandboxResponseTransformer = async (
	data: any,
): Promise<UpdateSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

const sandboxContentItemSchemaResponseTransformer = (data: any) => {
	if (data.size) {
		data.size = BigInt(data.size.toString());
	}
	return data;
};

const sandboxContentViewSchemaResponseTransformer = (data: any) => {
	if (data.contents) {
		data.contents = data.contents.map((item: any) =>
			sandboxContentItemSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getSandboxContentResponseTransformer = async (
	data: any,
): Promise<GetSandboxContentResponse> => {
	data = sandboxContentViewSchemaResponseTransformer(data);
	return data;
};

export const createSandboxDirectoryResponseTransformer = async (
	data: any,
): Promise<CreateSandboxDirectoryResponse> => {
	data = sandboxContentItemSchemaResponseTransformer(data);
	return data;
};

export const uploadSandboxFileResponseTransformer = async (
	data: any,
): Promise<UploadSandboxFileResponse> => {
	data = sandboxContentItemSchemaResponseTransformer(data);
	return data;
};

export const restartSandboxResponseTransformer = async (
	data: any,
): Promise<RestartSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

const shortSnapshotViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

const snapshotsViewSchemaResponseTransformer = (data: any) => {
	if (data.snapshots) {
		data.snapshots = data.snapshots.map((item: any) =>
			shortSnapshotViewSchemaResponseTransformer(item),
		);
	}
	return data;
};

export const getSandboxSnapshotsResponseTransformer = async (
	data: any,
): Promise<GetSandboxSnapshotsResponse> => {
	data = snapshotsViewSchemaResponseTransformer(data);
	return data;
};

const snapshotViewSchemaResponseTransformer = (data: any) => {
	if (data.create_date) {
		data.create_date = new Date(data.create_date);
	}
	return data;
};

export const addSandboxSnapshotResponseTransformer = async (
	data: any,
): Promise<AddSandboxSnapshotResponse> => {
	data = snapshotViewSchemaResponseTransformer(data);
	return data;
};

export const getSandboxSnapshotResponseTransformer = async (
	data: any,
): Promise<GetSandboxSnapshotResponse> => {
	data = snapshotViewSchemaResponseTransformer(data);
	return data;
};

export const startSandboxResponseTransformer = async (
	data: any,
): Promise<StartSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const stopSandboxResponseTransformer = async (
	data: any,
): Promise<StopSandboxResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const updateSandboxByYamlResponseTransformer = async (
	data: any,
): Promise<UpdateSandboxByYamlResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};

export const getProjectSnapshotsResponseTransformer = async (
	data: any,
): Promise<GetProjectSnapshotsResponse> => {
	data = snapshotsViewSchemaResponseTransformer(data);
	return data;
};

export const addSandboxByYamlResponseTransformer = async (
	data: any,
): Promise<AddSandboxByYamlResponse> => {
	data = sandboxResponseSchemaResponseTransformer(data);
	return data;
};
