// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl:
		| "https://schemas-openapi-buddy-swagger-ui-beta.eu-1.agent-sls.net"
		| (string & {});
};

export type UriBuilder = {
	[key: string]: unknown;
};

export type StatusType = {
	family?:
		| "INFORMATIONAL"
		| "SUCCESSFUL"
		| "REDIRECTION"
		| "CLIENT_ERROR"
		| "SERVER_ERROR"
		| "OTHER";
	status_code?: number;
	reason_phrase?: string;
};

export type Response = {
	status_info?: StatusType;
	allowed_methods?: Array<string>;
	cookies?: {
		[key: string]: NewCookie;
	};
	links?: Array<Link>;
	media_type?: MediaType;
	entity_tag?: EntityTag;
	string_headers?: {
		empty?: boolean;
		[key: string]: Array<string> | boolean | undefined;
	};
	closed?: boolean;
	length?: number;
	location?: string;
	language?: {
		language?: string;
		display_name?: string;
		country?: string;
		variant?: string;
		script?: string;
		unicode_locale_attributes?: Array<string>;
		unicode_locale_keys?: Array<string>;
		display_language?: string;
		display_script?: string;
		display_country?: string;
		display_variant?: string;
		extension_keys?: Array<string>;
		iso3_language?: string;
		iso3_country?: string;
	};
	date?: string;
	last_modified?: string;
	status?: number;
	metadata?: {
		empty?: boolean;
		[key: string]:
			| Array<{
					[key: string]: unknown;
			  }>
			| boolean
			| undefined;
	};
	entity?: {
		[key: string]: unknown;
	};
	headers?: {
		empty?: boolean;
		[key: string]:
			| Array<{
					[key: string]: unknown;
			  }>
			| boolean
			| undefined;
	};
};

export type EntityTag = {
	value?: string;
	weak?: boolean;
};

export type MediaType = {
	type?: string;
	subtype?: string;
	parameters?: {
		[key: string]: string;
	};
	wildcard_type?: boolean;
	wildcard_subtype?: boolean;
};

export type Link = {
	uri?: string;
	uri_builder?: UriBuilder;
	rel?: string;
	rels?: Array<string>;
	type?: string;
	params?: {
		[key: string]: string;
	};
	title?: string;
};

export type NewCookie = {
	name?: string;
	value?: string;
	version?: number;
	path?: string;
	domain?: string;
	comment?: string;
	max_age?: number;
	expiry?: string;
	secure?: boolean;
	http_only?: boolean;
	same_site?: "NONE" | "LAX" | "STRICT";
};

/**
 * Sandbox reference
 */
export type SandboxIdView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the sandbox
	 */
	id?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * The current status of the sandbox
	 */
	status?:
		| "STARTING"
		| "STOPPING"
		| "FAILED"
		| "RUNNING"
		| "STOPPED"
		| "RESTORING";
};

/**
 * Integration reference
 */
export type IntegrationIdView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * A human-readable ID of the integration
	 */
	identifier?: string;
	/**
	 * The unique hash ID of the integration
	 */
	hash_id?: string;
	/**
	 * The name of the integration
	 */
	name?: string;
	/**
	 * The type of integration
	 */
	type?:
		| "GIT_HUB"
		| "BITBUCKET"
		| "GOOGLE"
		| "DIGITAL_OCEAN"
		| "SLACK"
		| "MODULUS"
		| "HEROKU"
		| "AMAZON"
		| "GIT_LAB"
		| "SHOPIFY"
		| "GIT_HUB_ENTERPRISE"
		| "GIT_LAB_ENTERPRISE"
		| "PUSHOVER"
		| "PUSHBULLET"
		| "RACKSPACE"
		| "CUSTOM"
		| "CLOUDFLARE"
		| "NEW_RELIC"
		| "SENTRY"
		| "ROLLBAR"
		| "DATADOG"
		| "DO_SPACES"
		| "HONEYBADGER"
		| "VULTR"
		| "SENTRY_ENTERPRISE"
		| "LOGGLY"
		| "HIP_CHAT"
		| "FIREBASE"
		| "TELEGRAM"
		| "AZURE"
		| "UPCLOUD"
		| "GHOST_INSPECTOR"
		| "NETLIFY"
		| "AZURE_CLOUD"
		| "MICROSOFT_TEAMS"
		| "GOOGLE_SERVICE_ACCOUNT"
		| "GOOGLE_PLAY_STORE"
		| "DOCKER_HUB"
		| "APP_STORE"
		| "GIT_HUB_APP"
		| "GIT_HUB_APP_ENTERPRISE"
		| "GIT_HUB_API"
		| "ATOP"
		| "SNYK"
		| "STACK_HAWK"
		| "BLACKFIRE"
		| "BACKBLAZE"
		| "ONE_LOGIN"
		| "OKTA"
		| "CONTENTFUL";
	/**
	 * The authentication method used by the integration
	 */
	auth_type?:
		| "OAUTH"
		| "TOKEN"
		| "API_KEY"
		| "APP"
		| "APP_SPRYKER"
		| "TOKEN_APP_EXTENSION"
		| "DEFAULT"
		| "OIDC"
		| "TRUSTED"
		| "APP_RW";
	/**
	 * The host URL for custom integrations
	 */
	host_url?: string;
	/**
	 * The webhook URL for receiving notifications
	 */
	webhook_address?: string;
	/**
	 * The ATOP service URL
	 */
	atop_url?: string;
	/**
	 * The application ID for Azure Cloud integrations
	 */
	app_id?: string;
	/**
	 * The Google Cloud project ID
	 */
	google_project?: string;
	/**
	 * The JWT audience for token validation
	 */
	audience?: string;
};

/**
 * User/member reference
 */
export type MemberView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the user
	 */
	id?: number;
	/**
	 * The name of the user
	 */
	name?: string;
	/**
	 * The avatar URL of the user
	 */
	avatar_url?: string;
	/**
	 * The email address of the user
	 */
	email?: string;
	/**
	 * Whether the user has admin privileges
	 */
	admin?: boolean;
	/**
	 * Whether the user is workspace owner
	 */
	workspace_owner?: boolean;
};

export type ProjectView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The human-readable ID of the project
	 */
	name?: string;
	/**
	 * The Name of the project
	 */
	display_name: string;
	/**
	 * The status of the project
	 */
	status?: string;
	/**
	 * Indicates if this is a public project
	 */
	access?: "PRIVATE" | "PUBLIC";
	/**
	 * The creation date of the project
	 */
	create_date?: string;
	/**
	 * Repo slug of the Bitbucket, GitHub or GitLab project. Required when adding the integrated project
	 */
	external_project_id?: string;
	/**
	 * ID of the project in GitLab
	 */
	git_lab_project_id?: number;
	/**
	 * SSH or HTTPS url of the git repository. Required when adding the project integrated with custom git repository
	 */
	custom_repo_url?: string;
	/**
	 * Username used to authorize access to the git repository. Required when adding the project integrated with custom git repository
	 */
	custom_repo_user?: string;
	/**
	 * Password used to authorize access to the git repository. Required when adding the project integrated with custom git repository and the provided `custom_repo_url` is the HTTPS url
	 */
	custom_repo_pass?: string;
	/**
	 * The ID of the private SSH key used to authorize access to the git repository. Required when adding the project integrated with private git server by SSH url
	 */
	custom_repo_ssh_key_id?: number;
	created_by?: MemberView;
	/**
	 * The HTTP repository URL
	 */
	http_repository?: string;
	/**
	 * The SSH repository URL
	 */
	ssh_repository?: string;
	/**
	 * The default branch name
	 */
	default_branch?: string;
	integration?: IntegrationIdView;
	/**
	 * Defines whether the submodules are fetched during the runs in this project
	 */
	fetch_submodules?: boolean;
	/**
	 * Name of the key that will be used to authorize while fetching the submodules. Required when `fetch_submodules` is set to `true`
	 */
	fetch_submodules_env_key?: string;
	/**
	 * Enables/disables pull requests in the project. Available only for projects synchronized with GitHub or GitHub Enterprise repository
	 */
	allow_pull_requests?: boolean;
	/**
	 * If set to true, the default branch will be updated from GitHub/GitLab/Bitbucket.
	 */
	update_default_branch_from_external?: boolean;
	/**
	 * If set to true, the project is created without any repository attached.
	 */
	without_repository?: boolean;
};

export type UpdateSandboxRequest = {
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelView>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<AddVariableInObjectRequest>;
};

/**
 * The environment variables of the sandbox
 */
export type AddVariableInObjectRequest = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The name of the variable
	 */
	key: string;
	/**
	 * The value of the variable
	 */
	value?: string;
	/**
	 * If set to `true` the variable value can be set by Buddy actions
	 */
	settable?: boolean;
	/**
	 * Available only if `type=VAR`. If set to `true` the variable value can be set by Buddy actions only for execution time
	 */
	run_only_settable?: boolean;
	/**
	 * If set to `true` the variable value will be encrypted and hidden
	 */
	encrypted?: boolean;
	/**
	 * The optional description of the variable
	 */
	description?: string;
	/**
	 * Initial path for the variable
	 */
	init_path?: string;
	/**
	 * Default value for the variable
	 */
	defaults?: string;
	/**
	 * Specifies where to copy the file on each run. Set if `type` is `SSH_KEY`
	 */
	file_path?: string;
	/**
	 * File permission set on copy to a container on each run. Set if `type` is `SSH_KEY`
	 */
	file_chmod?: string;
	/**
	 * Set if `type` is `SSH_KEY`. If it's `NONE`, the variable can be used as a parameter in an action. For `CONTAINER`, the given key is additionally copied to an action container on each run
	 */
	file_place?: "NONE" | "CONTAINER";
	/**
	 * Password for certificates
	 */
	password?: string;
	/**
	 * Passphrase for encrypted SSH keys
	 */
	passphrase?: string;
	/**
	 * GPG key identifier
	 */
	key_identifier?: string;
	/**
	 * The type of the added variable. Can be one of `VAR` or `SSH_KEY`
	 */
	type:
		| "VAR"
		| "FILE"
		| "SSH_KEY"
		| "IOS_KEYCHAIN"
		| "IOS_PROVISION_PROFILES"
		| "SSH_PUBLIC_KEY"
		| "GPG_KEY";
};

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export type TlsSettingsView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * Where to terminate TLS connection
	 */
	terminate_at?: "REGION" | "AGENT" | "TARGET";
};

/**
 * The HTTP-specific settings of the tunnel
 */
export type HttpSettingsView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * Whether to verify SSL/TLS certificates
	 */
	verify_certificate?: boolean;
	/**
	 * Enable HTTP compression
	 */
	compression?: boolean;
	/**
	 * Enable HTTP/2 protocol support
	 */
	http2?: boolean;
	/**
	 * Log incoming HTTP requests
	 */
	log_requests?: boolean;
	/**
	 * Custom HTTP headers to add to requests
	 */
	request_headers?: Array<{
		[key: string]: string;
	}>;
	/**
	 * List of allowed User-Agent strings
	 */
	whitelist_user_agents?: Array<string>;
	/**
	 * Rewrite the Host header to this value
	 */
	rewrite_host_header?: string;
	/**
	 * Custom HTTP headers to add to responses
	 */
	response_headers?: Array<{
		[key: string]: string;
	}>;
	/**
	 * Basic authentication username
	 */
	login?: string;
	/**
	 * Circuit breaker threshold (number of failed requests)
	 */
	circuit_breaker?: number;
	/**
	 * Base path for serving requests
	 */
	serve_path?: string;
	/**
	 * Type of authentication used
	 */
	auth_type?: "NONE" | "BASIC" | "BUDDY";
};

export type TunnelView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The name of the tunnel
	 */
	name: string;
	/**
	 * The endpoint URL of the tunnel
	 */
	endpoint: string;
	/**
	 * The type of the tunnel
	 */
	type: "TCP" | "TLS" | "HTTP" | "SSH";
	/**
	 * The region where the tunnel is deployed
	 */
	region: "US" | "EU" | "AS";
	/**
	 * The IP addresses or domains allowed to access the tunnel
	 */
	whitelist?: Array<string>;
	/**
	 * The connection timeout of the tunnel in seconds
	 */
	timeout?: number;
	http?: HttpSettingsView;
	tls?: TlsSettingsView;
	/**
	 * The url of the tunnel
	 */
	endpoint_url?: string;
};

export type SandboxesView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	sandboxes?: Array<SandboxIdView>;
};

/**
 * Sandbox content listing
 */
export type SandboxContentView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * List of content items in the directory
	 */
	contents?: Array<SandboxContentItem>;
};

/**
 * Content item in a sandbox
 */
export type SandboxContentItem = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The content type (FILE or DIR)
	 */
	type?: "FILE" | "DIR";
	/**
	 * The name of the file or directory
	 */
	name?: string;
	/**
	 * The path to the file or directory
	 */
	path?: string;
	/**
	 * The size of the file in bytes
	 */
	size?: number;
};

export type SandboxCommandsView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	commands?: Array<SandboxCommandView>;
};

export type SandboxCommandView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the command
	 */
	id?: string;
	/**
	 * Command to execute in the sandbox
	 */
	command?: string;
	/**
	 * Runtime environment for command execution (default: `BASH`)
	 */
	runtime?: "BASH" | "JAVASCRIPT" | "TYPESCRIPT" | "PYTHON";
	/**
	 * Command execution status
	 */
	status?: "INPROGRESS" | "SUCCESSFUL" | "FAILED";
	/**
	 * Command exit code
	 */
	exit_code?: number;
	/**
	 * API endpoint URL to retrieve logs for this command
	 */
	logs_url?: string;
};

export type SandboxCommandLog = {
	/**
	 * The type of command output stream. `STDOUT` for standard output, `STDERR` for error output.
	 */
	type?: "STDOUT" | "STDERR";
	/**
	 * The command execution logs.
	 */
	data?: string;
};

export type SandboxAppLogsView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * Cursor for pagination
	 */
	cursor?: string;
	/**
	 * Application log entries
	 */
	logs?: Array<string>;
};

export type SnapshotsView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * Collection of snapshots
	 */
	snapshots?: Array<ShortSnapshotView>;
};

export type ShortSnapshotView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the snapshot
	 */
	id?: string;
	/**
	 * Snapshot name
	 */
	name?: string;
	/**
	 * Snapshot size in GB
	 */
	size?: number;
	/**
	 * Snapshot status
	 */
	status?: "CREATING" | "CREATED" | "DELETING" | "FAILED";
	/**
	 * Snapshot creation date
	 */
	create_date?: string;
};

export type ExecuteSandboxCommandRequest = {
	/**
	 * Command to execute in the sandbox
	 */
	command: string;
	/**
	 * Runtime environment for command execution (default: `BASH`)
	 */
	runtime?: "BASH" | "JAVASCRIPT" | "TYPESCRIPT" | "PYTHON";
};

export type AddSnapshotRequest = {
	/**
	 * Snapshot name
	 */
	name?: string;
};

export type SnapshotView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the snapshot
	 */
	id?: string;
	/**
	 * Snapshot name
	 */
	name?: string;
	/**
	 * Snapshot size in GB
	 */
	size?: number;
	/**
	 * Snapshot status
	 */
	status?: "CREATING" | "CREATED" | "DELETING" | "FAILED";
	/**
	 * Snapshot creation date
	 */
	create_date?: string;
	created_by?: MemberView;
};

export type SandboxYamlView = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The base64-encoded YAML configuration of the sandbox
	 */
	yaml?: string;
};

export type CreateNewSandboxRequest = {
	/**
	 * The name of the sandbox
	 */
	name: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelView>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<AddVariableInObjectRequest>;
};

export type CreateFromSnapshotRequest = {
	/**
	 * The ID of the snapshot to create from
	 */
	snapshot_id: string;
	/**
	 * The name of the sandbox
	 */
	name: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelView>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<EnvironmentVariableView>;
};

/**
 * The list of variables you can use the action
 */
export type EnvironmentVariableView = {
	/**
	 * The ID of the variable
	 */
	id?: number;
	/**
	 * The name of the variable
	 */
	key?: string;
	/**
	 * The value of the variable
	 */
	value?: string;
	/**
	 * The type of the added variable. Can be one of `VAR` or `SSH_KEY`
	 */
	type?:
		| "VAR"
		| "FILE"
		| "SSH_KEY"
		| "IOS_KEYCHAIN"
		| "IOS_PROVISION_PROFILES"
		| "SSH_PUBLIC_KEY"
		| "GPG_KEY";
	/**
	 * If set to `true` the variable value will be encrypted and hidden
	 */
	encrypted?: boolean;
	/**
	 * If set to `true` the variable value can be set by Buddy actions
	 */
	settable?: boolean;
	/**
	 * Available only if `type=VAR`. If set to `true` the variable value can be set by Buddy actions only for execution time
	 */
	run_only_settable?: boolean;
	/**
	 * The optional description of the variable
	 */
	description?: string;
	/**
	 * Initial path for the variable
	 */
	init_path?: string;
	/**
	 * Default value for the variable
	 */
	defaults?: string;
	/**
	 * Specifies where to copy the file on each run. Set if `type` is `SSH_KEY`
	 */
	file_path?: string;
	/**
	 * File permission set on copy to a container on each run. Set if `type` is `SSH_KEY`
	 */
	file_chmod?: string;
	/**
	 * Set if `type` is `SSH_KEY`. If it's `NONE`, the variable can be used as a parameter in an action. For `CONTAINER`, the given key is additionally copied to an action container on each run
	 */
	file_place?: "NONE" | "CONTAINER";
	/**
	 * Whether the file is binary
	 */
	binary?: boolean;
	/**
	 * Public value for SSH key type variables
	 */
	public_value?: string;
	/**
	 * Fingerprint of SSH key
	 */
	key_fingerprint?: string;
	/**
	 * Checksum of the variable value
	 */
	checksum?: string;
	/**
	 * Password for certificates
	 */
	password?: string;
	/**
	 * Passphrase for encrypted SSH keys
	 */
	passphrase?: string;
	/**
	 * GPG key identifier
	 */
	key_identifier?: string;
};

export type CloneSandboxRequest = {
	/**
	 * The ID of the sandbox to clone
	 */
	source_sandbox_id: string;
	/**
	 * The name of the sandbox
	 */
	name: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
};

export type SandboxResponse = {
	/**
	 * API endpoint to GET this object
	 */
	readonly url?: string;
	/**
	 * Web URL to view this object in Buddy.works
	 */
	readonly html_url?: string;
	/**
	 * The ID of the sandbox
	 */
	id?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * The current status of the sandbox
	 */
	status?:
		| "STARTING"
		| "STOPPING"
		| "FAILED"
		| "RUNNING"
		| "STOPPED"
		| "RESTORING";
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The current application status of the sandbox
	 */
	app_status?: "NONE" | "RUNNING" | "ENDED" | "FAILED";
	/**
	 * The boot logs of the sandbox
	 */
	boot_logs?: Array<string>;
	/**
	 * The current setup status of the sandbox
	 */
	setup_status?: "INPROGRESS" | "SUCCESS" | "FAILED";
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelView>;
	project?: ProjectView;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<EnvironmentVariableView>;
};

/**
 * Sandbox reference
 */
export type SandboxIdViewWritable = {
	/**
	 * The ID of the sandbox
	 */
	id?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * The current status of the sandbox
	 */
	status?:
		| "STARTING"
		| "STOPPING"
		| "FAILED"
		| "RUNNING"
		| "STOPPED"
		| "RESTORING";
};

/**
 * Integration reference
 */
export type IntegrationIdViewWritable = {
	/**
	 * A human-readable ID of the integration
	 */
	identifier?: string;
	/**
	 * The unique hash ID of the integration
	 */
	hash_id?: string;
	/**
	 * The name of the integration
	 */
	name?: string;
	/**
	 * The type of integration
	 */
	type?:
		| "GIT_HUB"
		| "BITBUCKET"
		| "GOOGLE"
		| "DIGITAL_OCEAN"
		| "SLACK"
		| "MODULUS"
		| "HEROKU"
		| "AMAZON"
		| "GIT_LAB"
		| "SHOPIFY"
		| "GIT_HUB_ENTERPRISE"
		| "GIT_LAB_ENTERPRISE"
		| "PUSHOVER"
		| "PUSHBULLET"
		| "RACKSPACE"
		| "CUSTOM"
		| "CLOUDFLARE"
		| "NEW_RELIC"
		| "SENTRY"
		| "ROLLBAR"
		| "DATADOG"
		| "DO_SPACES"
		| "HONEYBADGER"
		| "VULTR"
		| "SENTRY_ENTERPRISE"
		| "LOGGLY"
		| "HIP_CHAT"
		| "FIREBASE"
		| "TELEGRAM"
		| "AZURE"
		| "UPCLOUD"
		| "GHOST_INSPECTOR"
		| "NETLIFY"
		| "AZURE_CLOUD"
		| "MICROSOFT_TEAMS"
		| "GOOGLE_SERVICE_ACCOUNT"
		| "GOOGLE_PLAY_STORE"
		| "DOCKER_HUB"
		| "APP_STORE"
		| "GIT_HUB_APP"
		| "GIT_HUB_APP_ENTERPRISE"
		| "GIT_HUB_API"
		| "ATOP"
		| "SNYK"
		| "STACK_HAWK"
		| "BLACKFIRE"
		| "BACKBLAZE"
		| "ONE_LOGIN"
		| "OKTA"
		| "CONTENTFUL";
	/**
	 * The authentication method used by the integration
	 */
	auth_type?:
		| "OAUTH"
		| "TOKEN"
		| "API_KEY"
		| "APP"
		| "APP_SPRYKER"
		| "TOKEN_APP_EXTENSION"
		| "DEFAULT"
		| "OIDC"
		| "TRUSTED"
		| "APP_RW";
	/**
	 * The host URL for custom integrations
	 */
	host_url?: string;
	/**
	 * The webhook URL for receiving notifications
	 */
	webhook_address?: string;
	/**
	 * The ATOP service URL
	 */
	atop_url?: string;
	/**
	 * The application ID for Azure Cloud integrations
	 */
	app_id?: string;
	/**
	 * The Google Cloud project ID
	 */
	google_project?: string;
	/**
	 * The JWT audience for token validation
	 */
	audience?: string;
};

/**
 * User/member reference
 */
export type MemberViewWritable = {
	/**
	 * The ID of the user
	 */
	id?: number;
	/**
	 * The name of the user
	 */
	name?: string;
	/**
	 * The avatar URL of the user
	 */
	avatar_url?: string;
	/**
	 * The email address of the user
	 */
	email?: string;
	/**
	 * Whether the user has admin privileges
	 */
	admin?: boolean;
	/**
	 * Whether the user is workspace owner
	 */
	workspace_owner?: boolean;
};

export type ProjectViewWritable = {
	/**
	 * The human-readable ID of the project
	 */
	name?: string;
	/**
	 * The Name of the project
	 */
	display_name: string;
	/**
	 * The status of the project
	 */
	status?: string;
	/**
	 * Indicates if this is a public project
	 */
	access?: "PRIVATE" | "PUBLIC";
	/**
	 * The creation date of the project
	 */
	create_date?: string;
	/**
	 * Repo slug of the Bitbucket, GitHub or GitLab project. Required when adding the integrated project
	 */
	external_project_id?: string;
	/**
	 * ID of the project in GitLab
	 */
	git_lab_project_id?: number;
	/**
	 * SSH or HTTPS url of the git repository. Required when adding the project integrated with custom git repository
	 */
	custom_repo_url?: string;
	/**
	 * Username used to authorize access to the git repository. Required when adding the project integrated with custom git repository
	 */
	custom_repo_user?: string;
	/**
	 * Password used to authorize access to the git repository. Required when adding the project integrated with custom git repository and the provided `custom_repo_url` is the HTTPS url
	 */
	custom_repo_pass?: string;
	/**
	 * The ID of the private SSH key used to authorize access to the git repository. Required when adding the project integrated with private git server by SSH url
	 */
	custom_repo_ssh_key_id?: number;
	created_by?: MemberViewWritable;
	/**
	 * The HTTP repository URL
	 */
	http_repository?: string;
	/**
	 * The SSH repository URL
	 */
	ssh_repository?: string;
	/**
	 * The default branch name
	 */
	default_branch?: string;
	integration?: IntegrationIdViewWritable;
	/**
	 * Defines whether the submodules are fetched during the runs in this project
	 */
	fetch_submodules?: boolean;
	/**
	 * Name of the key that will be used to authorize while fetching the submodules. Required when `fetch_submodules` is set to `true`
	 */
	fetch_submodules_env_key?: string;
	/**
	 * Enables/disables pull requests in the project. Available only for projects synchronized with GitHub or GitHub Enterprise repository
	 */
	allow_pull_requests?: boolean;
	/**
	 * If set to true, the default branch will be updated from GitHub/GitLab/Bitbucket.
	 */
	update_default_branch_from_external?: boolean;
	/**
	 * If set to true, the project is created without any repository attached.
	 */
	without_repository?: boolean;
};

export type UpdateSandboxRequestWritable = {
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelViewWritable>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<AddVariableInObjectRequestWritable>;
};

/**
 * The environment variables of the sandbox
 */
export type AddVariableInObjectRequestWritable = {
	/**
	 * The name of the variable
	 */
	key: string;
	/**
	 * The value of the variable
	 */
	value?: string;
	/**
	 * If set to `true` the variable value can be set by Buddy actions
	 */
	settable?: boolean;
	/**
	 * Available only if `type=VAR`. If set to `true` the variable value can be set by Buddy actions only for execution time
	 */
	run_only_settable?: boolean;
	/**
	 * If set to `true` the variable value will be encrypted and hidden
	 */
	encrypted?: boolean;
	/**
	 * The optional description of the variable
	 */
	description?: string;
	/**
	 * Initial path for the variable
	 */
	init_path?: string;
	/**
	 * Default value for the variable
	 */
	defaults?: string;
	/**
	 * Specifies where to copy the file on each run. Set if `type` is `SSH_KEY`
	 */
	file_path?: string;
	/**
	 * File permission set on copy to a container on each run. Set if `type` is `SSH_KEY`
	 */
	file_chmod?: string;
	/**
	 * Set if `type` is `SSH_KEY`. If it's `NONE`, the variable can be used as a parameter in an action. For `CONTAINER`, the given key is additionally copied to an action container on each run
	 */
	file_place?: "NONE" | "CONTAINER";
	/**
	 * Password for certificates
	 */
	password?: string;
	/**
	 * Passphrase for encrypted SSH keys
	 */
	passphrase?: string;
	/**
	 * GPG key identifier
	 */
	key_identifier?: string;
	/**
	 * The type of the added variable. Can be one of `VAR` or `SSH_KEY`
	 */
	type:
		| "VAR"
		| "FILE"
		| "SSH_KEY"
		| "IOS_KEYCHAIN"
		| "IOS_PROVISION_PROFILES"
		| "SSH_PUBLIC_KEY"
		| "GPG_KEY";
};

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export type TlsSettingsViewWritable = {
	/**
	 * Private key for TLS certificate
	 */
	private_key?: string;
	/**
	 * TLS certificate
	 */
	certificate?: string;
	/**
	 * Certificate Authority certificate
	 */
	ca_certificate?: string;
	/**
	 * Where to terminate TLS connection
	 */
	terminate_at?: "REGION" | "AGENT" | "TARGET";
};

/**
 * The HTTP-specific settings of the tunnel
 */
export type HttpSettingsViewWritable = {
	/**
	 * Whether to verify SSL/TLS certificates
	 */
	verify_certificate?: boolean;
	/**
	 * Enable HTTP compression
	 */
	compression?: boolean;
	/**
	 * Enable HTTP/2 protocol support
	 */
	http2?: boolean;
	/**
	 * Log incoming HTTP requests
	 */
	log_requests?: boolean;
	/**
	 * Custom HTTP headers to add to requests
	 */
	request_headers?: Array<{
		[key: string]: string;
	}>;
	/**
	 * List of allowed User-Agent strings
	 */
	whitelist_user_agents?: Array<string>;
	/**
	 * Rewrite the Host header to this value
	 */
	rewrite_host_header?: string;
	/**
	 * Custom HTTP headers to add to responses
	 */
	response_headers?: Array<{
		[key: string]: string;
	}>;
	/**
	 * Basic authentication username
	 */
	login?: string;
	/**
	 * Basic authentication password
	 */
	password?: string;
	/**
	 * Custom TLS Certificate Authority
	 */
	tls_ca?: string;
	/**
	 * Circuit breaker threshold (number of failed requests)
	 */
	circuit_breaker?: number;
	/**
	 * Base path for serving requests
	 */
	serve_path?: string;
	/**
	 * Type of authentication used
	 */
	auth_type?: "NONE" | "BASIC" | "BUDDY";
};

export type TunnelViewWritable = {
	/**
	 * The name of the tunnel
	 */
	name: string;
	/**
	 * The endpoint URL of the tunnel
	 */
	endpoint: string;
	/**
	 * The type of the tunnel
	 */
	type: "TCP" | "TLS" | "HTTP" | "SSH";
	/**
	 * The region where the tunnel is deployed
	 */
	region: "US" | "EU" | "AS";
	/**
	 * The IP addresses or domains allowed to access the tunnel
	 */
	whitelist?: Array<string>;
	/**
	 * The connection timeout of the tunnel in seconds
	 */
	timeout?: number;
	http?: HttpSettingsViewWritable;
	tls?: TlsSettingsViewWritable;
	/**
	 * The url of the tunnel
	 */
	endpoint_url?: string;
};

export type SandboxesViewWritable = {
	sandboxes?: Array<SandboxIdViewWritable>;
};

/**
 * Sandbox content listing
 */
export type SandboxContentViewWritable = {
	/**
	 * List of content items in the directory
	 */
	contents?: Array<SandboxContentItemWritable>;
};

/**
 * Content item in a sandbox
 */
export type SandboxContentItemWritable = {
	/**
	 * The content type (FILE or DIR)
	 */
	type?: "FILE" | "DIR";
	/**
	 * The name of the file or directory
	 */
	name?: string;
	/**
	 * The path to the file or directory
	 */
	path?: string;
	/**
	 * The size of the file in bytes
	 */
	size?: number;
};

export type SandboxCommandsViewWritable = {
	commands?: Array<SandboxCommandViewWritable>;
};

export type SandboxCommandViewWritable = {
	/**
	 * The ID of the command
	 */
	id?: string;
	/**
	 * Command to execute in the sandbox
	 */
	command?: string;
	/**
	 * Runtime environment for command execution (default: `BASH`)
	 */
	runtime?: "BASH" | "JAVASCRIPT" | "TYPESCRIPT" | "PYTHON";
	/**
	 * Command execution status
	 */
	status?: "INPROGRESS" | "SUCCESSFUL" | "FAILED";
	/**
	 * Command exit code
	 */
	exit_code?: number;
	/**
	 * API endpoint URL to retrieve logs for this command
	 */
	logs_url?: string;
};

export type SandboxAppLogsViewWritable = {
	/**
	 * Cursor for pagination
	 */
	cursor?: string;
	/**
	 * Application log entries
	 */
	logs?: Array<string>;
};

export type SnapshotsViewWritable = {
	/**
	 * Collection of snapshots
	 */
	snapshots?: Array<ShortSnapshotViewWritable>;
};

export type ShortSnapshotViewWritable = {
	/**
	 * The ID of the snapshot
	 */
	id?: string;
	/**
	 * Snapshot name
	 */
	name?: string;
	/**
	 * Snapshot size in GB
	 */
	size?: number;
	/**
	 * Snapshot status
	 */
	status?: "CREATING" | "CREATED" | "DELETING" | "FAILED";
	/**
	 * Snapshot creation date
	 */
	create_date?: string;
};

export type SnapshotViewWritable = {
	/**
	 * The ID of the snapshot
	 */
	id?: string;
	/**
	 * Snapshot name
	 */
	name?: string;
	/**
	 * Snapshot size in GB
	 */
	size?: number;
	/**
	 * Snapshot status
	 */
	status?: "CREATING" | "CREATED" | "DELETING" | "FAILED";
	/**
	 * Snapshot creation date
	 */
	create_date?: string;
	created_by?: MemberViewWritable;
};

export type SandboxYamlViewWritable = {
	/**
	 * The base64-encoded YAML configuration of the sandbox
	 */
	yaml?: string;
};

export type CreateNewSandboxRequestWritable = {
	/**
	 * The name of the sandbox
	 */
	name: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelViewWritable>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<AddVariableInObjectRequestWritable>;
};

export type CreateFromSnapshotRequestWritable = {
	/**
	 * The ID of the snapshot to create from
	 */
	snapshot_id: string;
	/**
	 * The name of the sandbox
	 */
	name: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelViewWritable>;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<EnvironmentVariableView>;
};

export type SandboxResponseWritable = {
	/**
	 * The ID of the sandbox
	 */
	id?: string;
	/**
	 * A human-readable ID. Alphanumeric characters, underscores, and hyphens (hyphens cannot appear at the start or end).
	 */
	identifier?: string;
	/**
	 * The name of the sandbox
	 */
	name?: string;
	/**
	 * The current status of the sandbox
	 */
	status?:
		| "STARTING"
		| "STOPPING"
		| "FAILED"
		| "RUNNING"
		| "STOPPED"
		| "RESTORING";
	/**
	 * The operating system of the sandbox ["ubuntu:22.04", "ubuntu:24.04"]
	 */
	os?: string;
	/**
	 * The resource configuration of the sandbox (CPU x RAM)
	 */
	resources?:
		| "1x2"
		| "2x4"
		| "3x6"
		| "4x8"
		| "5x10"
		| "6x12"
		| "7x14"
		| "8x16"
		| "9x18"
		| "10x20"
		| "11x22"
		| "12x24"
		| "CUSTOM";
	/**
	 * The commands to run during setup of the sandbox
	 */
	install_commands?: string;
	/**
	 * The run command of the sandbox
	 */
	run_command?: string;
	/**
	 * The application directory of the sandbox
	 */
	app_dir?: string;
	/**
	 * The application type of the sandbox (passed command or existent service eg. apache2)
	 */
	app_type?: "CMD" | "SERVICE";
	/**
	 * The list of tags associated with the sandbox
	 */
	tags?: Array<string>;
	/**
	 * The current application status of the sandbox
	 */
	app_status?: "NONE" | "RUNNING" | "ENDED" | "FAILED";
	/**
	 * The boot logs of the sandbox
	 */
	boot_logs?: Array<string>;
	/**
	 * The current setup status of the sandbox
	 */
	setup_status?: "INPROGRESS" | "SUCCESS" | "FAILED";
	/**
	 * The tunnel endpoints of the sandbox
	 */
	endpoints?: Array<TunnelViewWritable>;
	project?: ProjectViewWritable;
	/**
	 * The environment variables of the sandbox
	 */
	variables?: Array<EnvironmentVariableView>;
};

export type GetSandboxesData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
	};
	query: {
		/**
		 * The human-readable ID of the project to filter sandboxes
		 */
		project_name: string;
	};
	url: "/workspaces/{workspace_domain}/sandboxes";
};

export type GetSandboxesResponses = {
	200: SandboxesView;
};

export type GetSandboxesResponse =
	GetSandboxesResponses[keyof GetSandboxesResponses];

export type AddSandboxData = {
	body?:
		| CloneSandboxRequest
		| CreateFromSnapshotRequestWritable
		| CreateNewSandboxRequestWritable;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
	};
	query: {
		/**
		 * The human-readable ID of the project to filter sandboxes
		 */
		project_name: string;
	};
	url: "/workspaces/{workspace_domain}/sandboxes";
};

export type AddSandboxResponses = {
	201: SandboxResponse;
};

export type AddSandboxResponse = AddSandboxResponses[keyof AddSandboxResponses];

export type DeleteSandboxData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{id}";
};

export type DeleteSandboxResponses = {
	/**
	 * Sandbox deleted successfully
	 */
	204: void;
};

export type DeleteSandboxResponse =
	DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{id}";
};

export type GetSandboxResponses = {
	200: SandboxResponse;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type UpdateSandboxData = {
	body?: UpdateSandboxRequestWritable;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{id}";
};

export type UpdateSandboxResponses = {
	200: SandboxResponse;
};

export type UpdateSandboxResponse =
	UpdateSandboxResponses[keyof UpdateSandboxResponses];

export type GetSandboxAppLogsData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: {
		/**
		 * Cursor for pagination
		 */
		cursor?: string;
	};
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/app-logs";
};

export type GetSandboxAppLogsResponses = {
	200: SandboxAppLogsView;
};

export type GetSandboxAppLogsResponse =
	GetSandboxAppLogsResponses[keyof GetSandboxAppLogsResponses];

export type GetSandboxCommandsData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/commands";
};

export type GetSandboxCommandsResponses = {
	200: SandboxCommandsView;
};

export type GetSandboxCommandsResponse =
	GetSandboxCommandsResponses[keyof GetSandboxCommandsResponses];

export type ExecuteSandboxCommandData = {
	body?: ExecuteSandboxCommandRequest;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/commands";
};

export type ExecuteSandboxCommandResponses = {
	200: SandboxCommandView;
};

export type ExecuteSandboxCommandResponse =
	ExecuteSandboxCommandResponses[keyof ExecuteSandboxCommandResponses];

export type GetSandboxCommandData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * The ID of the command
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/commands/{id}";
};

export type GetSandboxCommandResponses = {
	200: SandboxCommandView;
};

export type GetSandboxCommandResponse =
	GetSandboxCommandResponses[keyof GetSandboxCommandResponses];

export type GetSandboxCommandLogsData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * The ID of the command
		 */
		command_id: string;
	};
	query?: {
		/**
		 * If true, streams logs until the command completes
		 */
		follow?: boolean;
	};
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/commands/{command_id}/logs";
};

export type GetSandboxCommandLogsResponses = {
	200: SandboxCommandLog;
};

export type GetSandboxCommandLogsResponse =
	GetSandboxCommandLogsResponses[keyof GetSandboxCommandLogsResponses];

export type TerminateSandboxCommandData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * The ID of the command
		 */
		command_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/commands/{command_id}/terminate";
};

export type TerminateSandboxCommandResponses = {
	200: SandboxCommandView;
};

export type TerminateSandboxCommandResponse =
	TerminateSandboxCommandResponses[keyof TerminateSandboxCommandResponses];

export type DeleteSandboxFileData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * Absolute path to the file or directory to delete
		 */
		path: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/content/{path}";
};

export type DeleteSandboxFileResponses = {
	/**
	 * File or directory deleted successfully
	 */
	204: void;
};

export type DeleteSandboxFileResponse =
	DeleteSandboxFileResponses[keyof DeleteSandboxFileResponses];

export type GetSandboxContentData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * Absolute path to the file or directory. Recommended directory is `/buddy`
		 */
		path: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/content/{path}";
};

export type GetSandboxContentResponses = {
	/**
	 * Content retrieved successfully
	 */
	200: SandboxContentView;
};

export type GetSandboxContentResponse =
	GetSandboxContentResponses[keyof GetSandboxContentResponses];

export type CreateSandboxDirectoryData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * Absolute path where the directory should be created
		 */
		path: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/content/{path}";
};

export type CreateSandboxDirectoryErrors = {
	/**
	 * Directory already exists
	 */
	409: unknown;
};

export type CreateSandboxDirectoryResponses = {
	/**
	 * Directory created successfully
	 */
	201: SandboxContentItem;
};

export type CreateSandboxDirectoryResponse =
	CreateSandboxDirectoryResponses[keyof CreateSandboxDirectoryResponses];

export type UploadSandboxFileData = {
	/**
	 * File to upload
	 */
	body?: Blob | File;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * Absolute path where the file should be uploaded. Recommended directory is `/buddy`
		 */
		path: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/content/upload/{path}";
};

export type UploadSandboxFileResponses = {
	/**
	 * File uploaded successfully
	 */
	201: SandboxContentItem;
};

export type UploadSandboxFileResponse =
	UploadSandboxFileResponses[keyof UploadSandboxFileResponses];

export type DownloadSandboxContentData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * Absolute path to the file or directory to download
		 */
		path: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/download/{path}";
};

export type DownloadSandboxContentResponses = {
	/**
	 * Content downloaded successfully
	 */
	200: Response;
};

export type DownloadSandboxContentResponse =
	DownloadSandboxContentResponses[keyof DownloadSandboxContentResponses];

export type RestartSandboxData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/restart";
};

export type RestartSandboxResponses = {
	200: SandboxResponse;
};

export type RestartSandboxResponse =
	RestartSandboxResponses[keyof RestartSandboxResponses];

export type GetSandboxSnapshotsData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/snapshots";
};

export type GetSandboxSnapshotsResponses = {
	200: SnapshotsView;
};

export type GetSandboxSnapshotsResponse =
	GetSandboxSnapshotsResponses[keyof GetSandboxSnapshotsResponses];

export type AddSandboxSnapshotData = {
	body?: AddSnapshotRequest;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/snapshots";
};

export type AddSandboxSnapshotResponses = {
	201: SnapshotView;
};

export type AddSandboxSnapshotResponse =
	AddSandboxSnapshotResponses[keyof AddSandboxSnapshotResponses];

export type DeleteSandboxSnapshotData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * The ID of the snapshot
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/snapshots/{id}";
};

export type DeleteSandboxSnapshotResponses = {
	/**
	 * Sandbox snapshot deleted successfully
	 */
	204: void;
};

export type DeleteSandboxSnapshotResponse =
	DeleteSandboxSnapshotResponses[keyof DeleteSandboxSnapshotResponses];

export type GetSandboxSnapshotData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
		/**
		 * The ID of the snapshot
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/snapshots/{id}";
};

export type GetSandboxSnapshotResponses = {
	200: SnapshotView;
};

export type GetSandboxSnapshotResponse =
	GetSandboxSnapshotResponses[keyof GetSandboxSnapshotResponses];

export type StartSandboxData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/start";
};

export type StartSandboxResponses = {
	200: SandboxResponse;
};

export type StartSandboxResponse =
	StartSandboxResponses[keyof StartSandboxResponses];

export type StopSandboxData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/stop";
};

export type StopSandboxResponses = {
	200: SandboxResponse;
};

export type StopSandboxResponse =
	StopSandboxResponses[keyof StopSandboxResponses];

export type GetSandboxYamlData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/yaml";
};

export type GetSandboxYamlResponses = {
	200: SandboxYamlView;
};

export type GetSandboxYamlResponse =
	GetSandboxYamlResponses[keyof GetSandboxYamlResponses];

export type UpdateSandboxByYamlData = {
	body?: SandboxYamlViewWritable;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the sandbox
		 */
		sandbox_id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/{sandbox_id}/yaml";
};

export type UpdateSandboxByYamlResponses = {
	200: SandboxResponse;
};

export type UpdateSandboxByYamlResponse =
	UpdateSandboxByYamlResponses[keyof UpdateSandboxByYamlResponses];

export type GetProjectSnapshotsData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
	};
	query: {
		/**
		 * The human-readable ID of the project to filter sandboxes
		 */
		project_name: string;
	};
	url: "/workspaces/{workspace_domain}/sandboxes/snapshots";
};

export type GetProjectSnapshotsResponses = {
	200: SnapshotsView;
};

export type GetProjectSnapshotsResponse =
	GetProjectSnapshotsResponses[keyof GetProjectSnapshotsResponses];

export type DeleteSnapshotData = {
	body?: never;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
		/**
		 * The ID of the snapshot
		 */
		id: string;
	};
	query?: never;
	url: "/workspaces/{workspace_domain}/sandboxes/snapshots/{id}";
};

export type DeleteSnapshotResponses = {
	/**
	 * Sandbox snapshot deleted successfully
	 */
	204: void;
};

export type DeleteSnapshotResponse =
	DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type AddSandboxByYamlData = {
	body?: SandboxYamlViewWritable;
	path: {
		/**
		 * The human-readable ID of the workspace
		 */
		workspace_domain: string;
	};
	query: {
		/**
		 * The human-readable ID of the project to filter sandboxes
		 */
		project_name: string;
	};
	url: "/workspaces/{workspace_domain}/sandboxes/yaml";
};

export type AddSandboxByYamlResponses = {
	201: SandboxResponse;
};

export type AddSandboxByYamlResponse =
	AddSandboxByYamlResponses[keyof AddSandboxByYamlResponses];
