// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zUpdateWorkspaceMemberRequest = z.object({
	admin: z.optional(z.boolean()),
	auto_assign_to_new_projects: z.optional(z.boolean()),
	auto_assign_permission_set_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
});

export const zUpdateSsoRequest = z.object({
	type: z.optional(z.enum(["SAML", "OIDC"])),
	sso_provider_type: z.optional(
		z.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"]),
	),
	sso_url: z.optional(z.string()),
	issuer: z.optional(z.string()),
	certificate: z.optional(z.string()),
	signature_method: z.optional(z.string()),
	digest_method: z.optional(z.string()),
	client_id: z.optional(z.string()),
	client_secret: z.optional(z.string()),
	require_sso_for_all_members: z.optional(z.boolean()),
});

export const zGroupPermissionView = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	access_level: z.optional(
		z.enum([
			"DENIED",
			"READ_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
			"USE_ONLY",
		]),
	),
});

export const zUserPermissionView = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	access_level: z.optional(
		z.enum([
			"DENIED",
			"READ_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
			"USE_ONLY",
		]),
	),
});

/**
 * Permission settings defining who can use this integration
 */
export const zIntegrationPermissionsView = z.object({
	others: z.optional(
		z.enum([
			"DENIED",
			"READ_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
			"USE_ONLY",
		]),
	),
	users: z.optional(z.array(zUserPermissionView)),
	groups: z.optional(z.array(zGroupPermissionView)),
	admins: z.optional(
		z.enum([
			"DENIED",
			"READ_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
			"USE_ONLY",
		]),
	),
});

/**
 * Pipeline reference
 */
export const zPipelineIdView = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

export const zRoleAssumptionView = z.object({
	arn: z.optional(z.string()),
	external_id: z.optional(z.string()),
	duration: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
});

export const zUpdateIntegrationRequest = z.object({
	identifier: z.optional(z.string()),
	name: z.string(),
	token: z.optional(z.string()),
	email: z.optional(z.string()),
	api_key: z.optional(z.string()),
	access_key: z.optional(z.string()),
	secret_key: z.optional(z.string()),
	partner_token: z.optional(z.string()),
	shop: z.optional(z.string()),
	url: z.optional(z.string()),
	chat_id: z.optional(z.string()),
	git_hub_user_id: z.optional(z.string()),
	git_hub_user_name: z.optional(z.string()),
	username: z.optional(z.string()),
	password: z.optional(z.string()),
	app_id: z.optional(z.string()),
	tenant_id: z.optional(z.string()),
	client_id: z.optional(z.string()),
	client_token: z.optional(z.string()),
	server_id: z.optional(z.string()),
	server_token: z.optional(z.string()),
	key_id: z.optional(z.string()),
	application_key: z.optional(z.string()),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	slack_user_id: z.optional(z.string()),
	region: z.optional(z.string()),
	role_assumptions: z.optional(z.array(zRoleAssumptionView)),
	all_pipelines_allowed: z.optional(z.boolean()),
	allowed_pipelines: z.optional(z.array(zPipelineIdView)),
	permissions: z.optional(zIntegrationPermissionsView),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	target_url: z.optional(z.string()),
	refresh_token: z.optional(z.string()),
	audience: z.optional(z.string()),
	config: z.optional(z.string()),
	google_project: z.optional(z.string()),
	atop_url: z.optional(z.string()),
});

export const zShortWorkspaceView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	domain: z.optional(z.string()),
});

export const zWorkspacesView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	workspaces: z.optional(z.array(zShortWorkspaceView)),
});

export const zWorkspaceMemberView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	avatar_url: z.optional(z.string()),
	email: z.optional(z.string()),
	admin: z.optional(z.boolean()),
	workspace_owner: z.optional(z.boolean()),
	auto_assign_to_new_projects: z.optional(z.boolean()),
	auto_assign_permission_set_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
});

export const zWorkspaceMembersView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	members: z.optional(z.array(zWorkspaceMemberView)),
});

export const zWorkspaceView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	domain: z.optional(z.string()),
	owner_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	frozen: z.optional(z.boolean()),
	create_date: z.optional(z.iso.datetime()),
	default_pipeline_resource: z.optional(
		z.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		]),
	),
	sso_enabled: z.optional(z.boolean()),
	public_pipelines_disabled: z.optional(z.boolean()),
});

export const zSsoView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	type: z.optional(z.enum(["SAML", "OIDC"])),
	sso_provider_type: z.optional(
		z.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"]),
	),
	sso_url: z.optional(z.string()),
	issuer: z.optional(z.string()),
	certificate: z.optional(z.string()),
	signature_method: z.optional(z.string()),
	digest_method: z.optional(z.string()),
	require_sso_for_all_members: z.optional(z.boolean()),
});

/**
 * YAML pipeline definition configuration
 */
export const zYamlDefinitionView = z.object({
	path: z.optional(z.string()),
	branch: z.optional(z.string()),
	project: z.optional(z.string()),
});

/**
 * The parameters passed to the remote pipeline definition
 */
export const zPipelinePropertyView = z.object({
	key: z.optional(z.string()),
	value: z.optional(z.string()),
});

export const zPipelinePkgContextView = z.object({
	identifier: z.optional(z.string()),
	scope: z.optional(z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT", "ANY"])),
});

/**
 * The list of events that trigger the pipeline run
 */
export const zPipelineEventView = z.object({
	type: z.optional(
		z.enum([
			"PUSH",
			"CREATE_REF",
			"DELETE_REF",
			"PULL_REQUEST",
			"SCHEDULE",
			"PUBLISH_PACKAGE_VERSION",
			"DELETE_PACKAGE_VERSION",
			"WEBHOOK",
			"EMAIL",
			"CREATE_PACKAGE_VERSION",
		]),
	),
	refs: z.optional(z.array(z.string())),
	events: z.optional(z.array(z.string())),
	branches: z.optional(z.array(z.string())),
	packages: z.optional(z.array(zPipelinePkgContextView)),
	start_date: z.optional(z.iso.datetime()),
	delay: z.optional(
		z.coerce
			.bigint()
			.min(BigInt("-9223372036854775808"), {
				error: "Invalid value: Expected int64 to be >= -9223372036854775808",
			})
			.max(BigInt("9223372036854775807"), {
				error: "Invalid value: Expected int64 to be <= 9223372036854775807",
			}),
	),
	cron: z.optional(z.string()),
	timezone: z.optional(z.string()),
	totp: z.optional(z.boolean()),
	prefix: z.optional(z.string()),
	whitelist: z.optional(z.array(z.string())),
});

/**
 * Short representation of a pipeline
 */
export const zShortPipelineView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	definition_source: z.optional(z.enum(["LOCAL", "REMOTE"])),
	git_config_ref: z.optional(z.enum(["NONE", "DYNAMIC", "FIXED"])),
	refs: z.optional(z.array(z.string())),
	events: z.optional(z.array(zPipelineEventView)),
	loop: z.optional(z.array(z.string())),
	priority: z.optional(z.enum(["LOW", "NORMAL", "HIGH"])),
	disabled: z.optional(z.boolean()),
	disabled_reason: z.optional(z.string()),
	last_execution_status: z.optional(
		z.enum([
			"INPROGRESS",
			"ENQUEUED",
			"TERMINATED",
			"SUCCESSFUL",
			"FAILED",
			"INITIAL",
			"NOT_EXECUTED",
			"SKIPPED",
			"TERMINATING",
			"WAITING_FOR_APPLY",
			"WAITING_FOR_VARIABLES",
			"WAITING_FOR_SETTABLE_VARIABLES",
			"WAITING_FOR_VT_SESSION",
		]),
	),
	last_execution_revision: z.optional(z.string()),
	target_site_url: z.optional(z.string()),
	execution_message_template: z.optional(z.string()),
	create_date: z.optional(z.iso.datetime()),
	always_from_scratch: z.optional(z.boolean()),
	ignore_fail_on_project_status: z.optional(z.boolean()),
	no_skip_to_most_recent: z.optional(z.boolean()),
	terminate_stale_runs: z.optional(z.boolean()),
	auto_clear_cache: z.optional(z.boolean()),
	paused: z.optional(z.boolean()),
	pause_on_repeated_failures: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	fetch_all_refs: z.optional(z.boolean()),
	fail_on_prepare_env_warning: z.optional(z.boolean()),
	concurrent_pipeline_runs: z.optional(z.boolean()),
	clone_depth: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	do_not_create_commit_status: z.optional(z.boolean()),
	stale: z.optional(z.boolean()),
	waiting_for_push: z.optional(z.boolean()),
	resources: z.optional(
		z.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		]),
	),
	remote_path: z.optional(z.string()),
	remote_ref: z.optional(z.string()),
	remote_project_name: z.optional(z.string()),
	remote_parameters: z.optional(z.array(zPipelinePropertyView)),
	git_config: z.optional(zYamlDefinitionView),
	tags: z.optional(z.array(z.string())),
	git_changeset_base: z.optional(
		z.enum(["LATEST_RUN", "LATEST_RUN_MATCHING_REF", "PULL_REQUEST"]),
	),
	filesystem_changeset_base: z.optional(z.enum(["DATE_MODIFIED", "CONTENTS"])),
	cpu: z.optional(z.enum(["X64", "ARM", "X86"])),
	description_required: z.optional(z.boolean()),
	folder: z.optional(z.string()),
});

/**
 * The integration to use for authentication
 */
export const zIntegrationView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	identifier: z.optional(z.string()),
	hash_id: z.optional(z.string()),
	name: z.optional(z.string()),
	type: z.optional(
		z.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
		]),
	),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	scope: z.optional(z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"])),
	project_name: z.optional(z.string()),
	app_id: z.optional(z.string()),
	google_project: z.optional(z.string()),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	audience: z.optional(z.string()),
	atop_url: z.optional(z.string()),
	permissions: z.optional(zIntegrationPermissionsView),
	all_pipelines_allowed: z.optional(z.boolean()),
	allowed_pipelines: z.optional(z.array(zShortPipelineView)),
});

export const zIntegrationsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	integrations: z.optional(z.array(zIntegrationView)),
});

export const zIdsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	domain: z.optional(z.string()),
	project_identifier: z.optional(z.string()),
	pipeline_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	environment_id: z.optional(z.string()),
	pkg_id: z.optional(z.string()),
	pkg_version_id: z.optional(z.string()),
	sandbox_id: z.optional(z.string()),
});

export const zAddWorkspaceMemberRequest = z.object({
	admin: z.optional(z.boolean()),
	auto_assign_to_new_projects: z.optional(z.boolean()),
	auto_assign_permission_set_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	email: z.string(),
});

export const zAddIntegrationRequest = z.object({
	identifier: z.optional(z.string()),
	name: z.string(),
	token: z.optional(z.string()),
	email: z.optional(z.string()),
	api_key: z.optional(z.string()),
	access_key: z.optional(z.string()),
	secret_key: z.optional(z.string()),
	partner_token: z.optional(z.string()),
	shop: z.optional(z.string()),
	url: z.optional(z.string()),
	chat_id: z.optional(z.string()),
	git_hub_user_id: z.optional(z.string()),
	git_hub_user_name: z.optional(z.string()),
	username: z.optional(z.string()),
	password: z.optional(z.string()),
	app_id: z.optional(z.string()),
	tenant_id: z.optional(z.string()),
	client_id: z.optional(z.string()),
	client_token: z.optional(z.string()),
	server_id: z.optional(z.string()),
	server_token: z.optional(z.string()),
	key_id: z.optional(z.string()),
	application_key: z.optional(z.string()),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	slack_user_id: z.optional(z.string()),
	region: z.optional(z.string()),
	role_assumptions: z.optional(z.array(zRoleAssumptionView)),
	all_pipelines_allowed: z.optional(z.boolean()),
	allowed_pipelines: z.optional(z.array(zPipelineIdView)),
	permissions: z.optional(zIntegrationPermissionsView),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	target_url: z.optional(z.string()),
	refresh_token: z.optional(z.string()),
	audience: z.optional(z.string()),
	config: z.optional(z.string()),
	google_project: z.optional(z.string()),
	atop_url: z.optional(z.string()),
	type: z.enum([
		"GIT_HUB",
		"BITBUCKET",
		"GOOGLE",
		"DIGITAL_OCEAN",
		"SLACK",
		"MODULUS",
		"HEROKU",
		"AMAZON",
		"GIT_LAB",
		"SHOPIFY",
		"GIT_HUB_ENTERPRISE",
		"GIT_LAB_ENTERPRISE",
		"PUSHOVER",
		"PUSHBULLET",
		"RACKSPACE",
		"CUSTOM",
		"CLOUDFLARE",
		"NEW_RELIC",
		"SENTRY",
		"ROLLBAR",
		"DATADOG",
		"DO_SPACES",
		"HONEYBADGER",
		"VULTR",
		"SENTRY_ENTERPRISE",
		"LOGGLY",
		"HIP_CHAT",
		"FIREBASE",
		"TELEGRAM",
		"AZURE",
		"UPCLOUD",
		"GHOST_INSPECTOR",
		"NETLIFY",
		"AZURE_CLOUD",
		"MICROSOFT_TEAMS",
		"GOOGLE_SERVICE_ACCOUNT",
		"GOOGLE_PLAY_STORE",
		"DOCKER_HUB",
		"APP_STORE",
		"GIT_HUB_APP",
		"GIT_HUB_APP_ENTERPRISE",
		"GIT_HUB_API",
		"ATOP",
		"SNYK",
		"STACK_HAWK",
		"BLACKFIRE",
		"BACKBLAZE",
		"ONE_LOGIN",
		"OKTA",
		"CONTENTFUL",
	]),
	scope: z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"]),
	project_name: z.optional(z.string()),
});

/**
 * Sandbox reference
 */
export const zSandboxIdView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(z.string()),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	status: z.optional(
		z.enum([
			"STARTING",
			"STOPPING",
			"FAILED",
			"RUNNING",
			"STOPPED",
			"RESTORING",
		]),
	),
});

/**
 * Integration reference
 */
export const zIntegrationIdView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	identifier: z.optional(z.string()),
	hash_id: z.optional(z.string()),
	name: z.optional(z.string()),
	type: z.optional(
		z.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
		]),
	),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	atop_url: z.optional(z.string()),
	app_id: z.optional(z.string()),
	google_project: z.optional(z.string()),
	audience: z.optional(z.string()),
});

/**
 * User/member reference
 */
export const zMemberView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	avatar_url: z.optional(z.string()),
	email: z.optional(z.string()),
	admin: z.optional(z.boolean()),
	workspace_owner: z.optional(z.boolean()),
});

export const zProjectView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	name: z.optional(z.string()),
	display_name: z.string(),
	status: z.optional(z.string()),
	access: z.optional(z.enum(["PRIVATE", "PUBLIC"])),
	create_date: z.optional(z.iso.datetime()),
	external_project_id: z.optional(z.string()),
	git_lab_project_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	custom_repo_url: z.optional(z.string()),
	custom_repo_user: z.optional(z.string()),
	custom_repo_pass: z.optional(z.string()),
	custom_repo_ssh_key_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	created_by: z.optional(zMemberView),
	http_repository: z.optional(z.string()),
	ssh_repository: z.optional(z.string()),
	default_branch: z.optional(z.string()),
	integration: z.optional(zIntegrationIdView),
	fetch_submodules: z.optional(z.boolean()),
	fetch_submodules_env_key: z.optional(z.string()),
	allow_pull_requests: z.optional(z.boolean()),
	update_default_branch_from_external: z.optional(z.boolean()),
	without_repository: z.optional(z.boolean()),
});

/**
 * Access permissions configuration
 */
export const zPermissionsView = z.object({
	others: z.optional(
		z.enum([
			"DENIED",
			"READ_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
			"USE_ONLY",
		]),
	),
	users: z.optional(z.array(zUserPermissionView)),
	groups: z.optional(z.array(zGroupPermissionView)),
});

/**
 * Short representation of a project
 */
export const zShortProjectView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	name: z.optional(z.string()),
	display_name: z.string(),
	status: z.optional(z.string()),
	access: z.optional(z.enum(["PRIVATE", "PUBLIC"])),
	create_date: z.optional(z.iso.datetime()),
});

/**
 * The environment variables of the sandbox
 */
export const zAddVariableInObjectRequest = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	key: z.string(),
	value: z.optional(z.string()),
	settable: z.optional(z.boolean()),
	run_only_settable: z.optional(z.boolean()),
	encrypted: z.optional(z.boolean()),
	description: z.optional(z.string()),
	init_path: z.optional(z.string()),
	defaults: z.optional(z.string()),
	file_path: z.optional(z.string()),
	file_chmod: z.optional(z.string()),
	file_place: z.optional(z.enum(["NONE", "CONTAINER"])),
	password: z.optional(z.string()),
	passphrase: z.optional(z.string()),
	key_identifier: z.optional(z.string()),
	type: z.enum([
		"VAR",
		"FILE",
		"SSH_KEY",
		"IOS_KEYCHAIN",
		"IOS_PROVISION_PROFILES",
		"SSH_PUBLIC_KEY",
		"GPG_KEY",
	]),
});

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export const zTlsSettingsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	terminate_at: z.optional(z.enum(["REGION", "AGENT", "TARGET"])),
});

/**
 * The HTTP-specific settings of the tunnel
 */
export const zHttpSettingsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	verify_certificate: z.optional(z.boolean()),
	compression: z.optional(z.boolean()),
	http2: z.optional(z.boolean()),
	log_requests: z.optional(z.boolean()),
	request_headers: z.optional(z.array(z.record(z.string(), z.string()))),
	whitelist_user_agents: z.optional(z.array(z.string())),
	rewrite_host_header: z.optional(z.string()),
	response_headers: z.optional(z.array(z.record(z.string(), z.string()))),
	login: z.optional(z.string()),
	circuit_breaker: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	serve_path: z.optional(z.string()),
	auth_type: z.optional(z.enum(["NONE", "BASIC", "BUDDY"])),
});

export const zTunnelView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	name: z.string(),
	endpoint: z.string(),
	type: z.enum(["TCP", "TLS", "HTTP", "SSH"]),
	region: z.enum(["US", "EU", "AS"]),
	whitelist: z.optional(z.array(z.string())),
	timeout: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	http: z.optional(zHttpSettingsView),
	tls: z.optional(zTlsSettingsView),
	endpoint_url: z.optional(z.string()),
});

export const zUpdateSandboxRequest = z.object({
	name: z.optional(z.string()),
	identifier: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelView)),
	variables: z.optional(z.array(zAddVariableInObjectRequest)),
	permissions: z.optional(zPermissionsView),
});

export const zSandboxesView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	sandboxes: z.optional(z.array(zSandboxIdView)),
});

/**
 * Content item in a sandbox
 */
export const zSandboxContentItem = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	type: z.optional(z.enum(["FILE", "DIR"])),
	name: z.optional(z.string()),
	path: z.optional(z.string()),
	size: z.optional(
		z.coerce
			.bigint()
			.min(BigInt("-9223372036854775808"), {
				error: "Invalid value: Expected int64 to be >= -9223372036854775808",
			})
			.max(BigInt("9223372036854775807"), {
				error: "Invalid value: Expected int64 to be <= 9223372036854775807",
			}),
	),
});

/**
 * Sandbox content listing
 */
export const zSandboxContentView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	contents: z.optional(z.array(zSandboxContentItem)),
});

export const zSandboxCommandView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(z.string()),
	command: z.optional(z.string()),
	runtime: z.optional(z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"])),
	status: z.optional(z.enum(["INPROGRESS", "SUCCESSFUL", "FAILED"])),
	exit_code: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	logs_url: z.optional(z.string()),
});

export const zSandboxCommandsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	commands: z.optional(z.array(zSandboxCommandView)),
});

export const zSandboxCommandLog = z.object({
	type: z.optional(z.enum(["STDOUT", "STDERR"])),
	data: z.optional(z.string()),
});

export const zSandboxAppLogsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	cursor: z.optional(z.string()),
	logs: z.optional(z.array(z.string())),
});

export const zShortSnapshotView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(z.string()),
	name: z.optional(z.string()),
	size: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	status: z.optional(z.enum(["CREATING", "CREATED", "DELETING", "FAILED"])),
	create_date: z.optional(z.iso.datetime()),
});

export const zSnapshotsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	snapshots: z.optional(z.array(zShortSnapshotView)),
});

export const zExecuteSandboxCommandRequest = z.object({
	command: z.string(),
	runtime: z.optional(z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"])),
});

export const zAddSnapshotRequest = z.object({
	name: z.optional(z.string()),
});

export const zSnapshotView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(z.string()),
	name: z.optional(z.string()),
	size: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	status: z.optional(z.enum(["CREATING", "CREATED", "DELETING", "FAILED"])),
	create_date: z.optional(z.iso.datetime()),
	created_by: z.optional(zMemberView),
});

export const zSandboxYamlView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	yaml: z.optional(z.string()),
});

export const zCreateNewSandboxRequest = z.object({
	name: z.string(),
	identifier: z.optional(z.string()),
	os: z.string(),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelView)),
	variables: z.optional(z.array(zAddVariableInObjectRequest)),
});

/**
 * The list of variables you can use the action
 */
export const zEnvironmentVariableView = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	key: z.optional(z.string()),
	value: z.optional(z.string()),
	type: z.optional(
		z.enum([
			"VAR",
			"FILE",
			"SSH_KEY",
			"IOS_KEYCHAIN",
			"IOS_PROVISION_PROFILES",
			"SSH_PUBLIC_KEY",
			"GPG_KEY",
		]),
	),
	encrypted: z.optional(z.boolean()),
	settable: z.optional(z.boolean()),
	run_only_settable: z.optional(z.boolean()),
	description: z.optional(z.string()),
	init_path: z.optional(z.string()),
	defaults: z.optional(z.string()),
	file_path: z.optional(z.string()),
	file_chmod: z.optional(z.string()),
	file_place: z.optional(z.enum(["NONE", "CONTAINER"])),
	binary: z.optional(z.boolean()),
	public_value: z.optional(z.string()),
	key_fingerprint: z.optional(z.string()),
	checksum: z.optional(z.string()),
	password: z.optional(z.string()),
	passphrase: z.optional(z.string()),
	key_identifier: z.optional(z.string()),
});

export const zCreateFromSnapshotRequest = z.object({
	snapshot_id: z.string(),
	name: z.string(),
	identifier: z.optional(z.string()),
	os: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelView)),
	variables: z.optional(z.array(zEnvironmentVariableView)),
});

export const zCloneSandboxRequest = z.object({
	source_sandbox_id: z.string(),
	name: z.string(),
	identifier: z.optional(z.string()),
});

export const zSandboxResponse = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	id: z.optional(z.string()),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	status: z.optional(
		z.enum([
			"STARTING",
			"STOPPING",
			"FAILED",
			"RUNNING",
			"STOPPED",
			"RESTORING",
		]),
	),
	os: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	app_status: z.optional(z.enum(["NONE", "RUNNING", "ENDED", "FAILED"])),
	boot_logs: z.optional(z.array(z.string())),
	setup_status: z.optional(z.enum(["INPROGRESS", "SUCCESS", "FAILED"])),
	endpoints: z.optional(z.array(zTunnelView)),
	project: z.optional(zProjectView),
	permissions: z.optional(zPermissionsView),
	variables: z.optional(z.array(zEnvironmentVariableView)),
});

export const zProjectsView = z.object({
	url: z.optional(z.string().readonly()),
	html_url: z.optional(z.string().readonly()),
	projects: z.optional(z.array(zShortProjectView)),
});

export const zShortWorkspaceViewWritable = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	domain: z.optional(z.string()),
});

export const zWorkspacesViewWritable = z.object({
	workspaces: z.optional(z.array(zShortWorkspaceViewWritable)),
});

export const zWorkspaceMemberViewWritable = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	avatar_url: z.optional(z.string()),
	email: z.optional(z.string()),
	admin: z.optional(z.boolean()),
	workspace_owner: z.optional(z.boolean()),
	auto_assign_to_new_projects: z.optional(z.boolean()),
	auto_assign_permission_set_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
});

export const zWorkspaceMembersViewWritable = z.object({
	members: z.optional(z.array(zWorkspaceMemberViewWritable)),
});

export const zWorkspaceViewWritable = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	domain: z.optional(z.string()),
	owner_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	frozen: z.optional(z.boolean()),
	create_date: z.optional(z.iso.datetime()),
	default_pipeline_resource: z.optional(
		z.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		]),
	),
	sso_enabled: z.optional(z.boolean()),
	public_pipelines_disabled: z.optional(z.boolean()),
});

export const zSsoViewWritable = z.object({
	type: z.optional(z.enum(["SAML", "OIDC"])),
	sso_provider_type: z.optional(
		z.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"]),
	),
	sso_url: z.optional(z.string()),
	issuer: z.optional(z.string()),
	certificate: z.optional(z.string()),
	signature_method: z.optional(z.string()),
	digest_method: z.optional(z.string()),
	require_sso_for_all_members: z.optional(z.boolean()),
});

/**
 * Short representation of a pipeline
 */
export const zShortPipelineViewWritable = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	definition_source: z.optional(z.enum(["LOCAL", "REMOTE"])),
	git_config_ref: z.optional(z.enum(["NONE", "DYNAMIC", "FIXED"])),
	refs: z.optional(z.array(z.string())),
	events: z.optional(z.array(zPipelineEventView)),
	loop: z.optional(z.array(z.string())),
	priority: z.optional(z.enum(["LOW", "NORMAL", "HIGH"])),
	disabled: z.optional(z.boolean()),
	disabled_reason: z.optional(z.string()),
	last_execution_status: z.optional(
		z.enum([
			"INPROGRESS",
			"ENQUEUED",
			"TERMINATED",
			"SUCCESSFUL",
			"FAILED",
			"INITIAL",
			"NOT_EXECUTED",
			"SKIPPED",
			"TERMINATING",
			"WAITING_FOR_APPLY",
			"WAITING_FOR_VARIABLES",
			"WAITING_FOR_SETTABLE_VARIABLES",
			"WAITING_FOR_VT_SESSION",
		]),
	),
	last_execution_revision: z.optional(z.string()),
	target_site_url: z.optional(z.string()),
	execution_message_template: z.optional(z.string()),
	create_date: z.optional(z.iso.datetime()),
	always_from_scratch: z.optional(z.boolean()),
	ignore_fail_on_project_status: z.optional(z.boolean()),
	no_skip_to_most_recent: z.optional(z.boolean()),
	terminate_stale_runs: z.optional(z.boolean()),
	auto_clear_cache: z.optional(z.boolean()),
	paused: z.optional(z.boolean()),
	pause_on_repeated_failures: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	fetch_all_refs: z.optional(z.boolean()),
	fail_on_prepare_env_warning: z.optional(z.boolean()),
	concurrent_pipeline_runs: z.optional(z.boolean()),
	clone_depth: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	do_not_create_commit_status: z.optional(z.boolean()),
	stale: z.optional(z.boolean()),
	waiting_for_push: z.optional(z.boolean()),
	resources: z.optional(
		z.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		]),
	),
	remote_path: z.optional(z.string()),
	remote_ref: z.optional(z.string()),
	remote_project_name: z.optional(z.string()),
	remote_parameters: z.optional(z.array(zPipelinePropertyView)),
	git_config: z.optional(zYamlDefinitionView),
	tags: z.optional(z.array(z.string())),
	git_changeset_base: z.optional(
		z.enum(["LATEST_RUN", "LATEST_RUN_MATCHING_REF", "PULL_REQUEST"]),
	),
	filesystem_changeset_base: z.optional(z.enum(["DATE_MODIFIED", "CONTENTS"])),
	cpu: z.optional(z.enum(["X64", "ARM", "X86"])),
	description_required: z.optional(z.boolean()),
	folder: z.optional(z.string()),
});

/**
 * The integration to use for authentication
 */
export const zIntegrationViewWritable = z.object({
	identifier: z.optional(z.string()),
	hash_id: z.optional(z.string()),
	name: z.optional(z.string()),
	type: z.optional(
		z.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
		]),
	),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	scope: z.optional(z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"])),
	project_name: z.optional(z.string()),
	app_id: z.optional(z.string()),
	google_project: z.optional(z.string()),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	audience: z.optional(z.string()),
	atop_url: z.optional(z.string()),
	permissions: z.optional(zIntegrationPermissionsView),
	all_pipelines_allowed: z.optional(z.boolean()),
	allowed_pipelines: z.optional(z.array(zShortPipelineViewWritable)),
});

export const zIntegrationsViewWritable = z.object({
	integrations: z.optional(z.array(zIntegrationViewWritable)),
});

export const zIdsViewWritable = z.object({
	domain: z.optional(z.string()),
	project_identifier: z.optional(z.string()),
	pipeline_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	environment_id: z.optional(z.string()),
	pkg_id: z.optional(z.string()),
	pkg_version_id: z.optional(z.string()),
	sandbox_id: z.optional(z.string()),
});

/**
 * Sandbox reference
 */
export const zSandboxIdViewWritable = z.object({
	id: z.optional(z.string()),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	status: z.optional(
		z.enum([
			"STARTING",
			"STOPPING",
			"FAILED",
			"RUNNING",
			"STOPPED",
			"RESTORING",
		]),
	),
});

/**
 * Integration reference
 */
export const zIntegrationIdViewWritable = z.object({
	identifier: z.optional(z.string()),
	hash_id: z.optional(z.string()),
	name: z.optional(z.string()),
	type: z.optional(
		z.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
		]),
	),
	auth_type: z.optional(
		z.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		]),
	),
	host_url: z.optional(z.string()),
	webhook_address: z.optional(z.string()),
	atop_url: z.optional(z.string()),
	app_id: z.optional(z.string()),
	google_project: z.optional(z.string()),
	audience: z.optional(z.string()),
});

/**
 * User/member reference
 */
export const zMemberViewWritable = z.object({
	id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	name: z.optional(z.string()),
	avatar_url: z.optional(z.string()),
	email: z.optional(z.string()),
	admin: z.optional(z.boolean()),
	workspace_owner: z.optional(z.boolean()),
});

export const zProjectViewWritable = z.object({
	name: z.optional(z.string()),
	display_name: z.string(),
	status: z.optional(z.string()),
	access: z.optional(z.enum(["PRIVATE", "PUBLIC"])),
	create_date: z.optional(z.iso.datetime()),
	external_project_id: z.optional(z.string()),
	git_lab_project_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	custom_repo_url: z.optional(z.string()),
	custom_repo_user: z.optional(z.string()),
	custom_repo_pass: z.optional(z.string()),
	custom_repo_ssh_key_id: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	created_by: z.optional(zMemberViewWritable),
	http_repository: z.optional(z.string()),
	ssh_repository: z.optional(z.string()),
	default_branch: z.optional(z.string()),
	integration: z.optional(zIntegrationIdViewWritable),
	fetch_submodules: z.optional(z.boolean()),
	fetch_submodules_env_key: z.optional(z.string()),
	allow_pull_requests: z.optional(z.boolean()),
	update_default_branch_from_external: z.optional(z.boolean()),
	without_repository: z.optional(z.boolean()),
});

/**
 * Short representation of a project
 */
export const zShortProjectViewWritable = z.object({
	name: z.optional(z.string()),
	display_name: z.string(),
	status: z.optional(z.string()),
	access: z.optional(z.enum(["PRIVATE", "PUBLIC"])),
	create_date: z.optional(z.iso.datetime()),
});

/**
 * The environment variables of the sandbox
 */
export const zAddVariableInObjectRequestWritable = z.object({
	key: z.string(),
	value: z.optional(z.string()),
	settable: z.optional(z.boolean()),
	run_only_settable: z.optional(z.boolean()),
	encrypted: z.optional(z.boolean()),
	description: z.optional(z.string()),
	init_path: z.optional(z.string()),
	defaults: z.optional(z.string()),
	file_path: z.optional(z.string()),
	file_chmod: z.optional(z.string()),
	file_place: z.optional(z.enum(["NONE", "CONTAINER"])),
	password: z.optional(z.string()),
	passphrase: z.optional(z.string()),
	key_identifier: z.optional(z.string()),
	type: z.enum([
		"VAR",
		"FILE",
		"SSH_KEY",
		"IOS_KEYCHAIN",
		"IOS_PROVISION_PROFILES",
		"SSH_PUBLIC_KEY",
		"GPG_KEY",
	]),
});

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export const zTlsSettingsViewWritable = z.object({
	private_key: z.optional(z.string()),
	certificate: z.optional(z.string()),
	ca_certificate: z.optional(z.string()),
	terminate_at: z.optional(z.enum(["REGION", "AGENT", "TARGET"])),
});

/**
 * The HTTP-specific settings of the tunnel
 */
export const zHttpSettingsViewWritable = z.object({
	verify_certificate: z.optional(z.boolean()),
	compression: z.optional(z.boolean()),
	http2: z.optional(z.boolean()),
	log_requests: z.optional(z.boolean()),
	request_headers: z.optional(z.array(z.record(z.string(), z.string()))),
	whitelist_user_agents: z.optional(z.array(z.string())),
	rewrite_host_header: z.optional(z.string()),
	response_headers: z.optional(z.array(z.record(z.string(), z.string()))),
	login: z.optional(z.string()),
	password: z.optional(z.string()),
	tls_ca: z.optional(z.string()),
	circuit_breaker: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	serve_path: z.optional(z.string()),
	auth_type: z.optional(z.enum(["NONE", "BASIC", "BUDDY"])),
});

export const zTunnelViewWritable = z.object({
	name: z.string(),
	endpoint: z.string(),
	type: z.enum(["TCP", "TLS", "HTTP", "SSH"]),
	region: z.enum(["US", "EU", "AS"]),
	whitelist: z.optional(z.array(z.string())),
	timeout: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	http: z.optional(zHttpSettingsViewWritable),
	tls: z.optional(zTlsSettingsViewWritable),
	endpoint_url: z.optional(z.string()),
});

export const zUpdateSandboxRequestWritable = z.object({
	name: z.optional(z.string()),
	identifier: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelViewWritable)),
	variables: z.optional(z.array(zAddVariableInObjectRequestWritable)),
	permissions: z.optional(zPermissionsView),
});

export const zSandboxesViewWritable = z.object({
	sandboxes: z.optional(z.array(zSandboxIdViewWritable)),
});

/**
 * Content item in a sandbox
 */
export const zSandboxContentItemWritable = z.object({
	type: z.optional(z.enum(["FILE", "DIR"])),
	name: z.optional(z.string()),
	path: z.optional(z.string()),
	size: z.optional(
		z.coerce
			.bigint()
			.min(BigInt("-9223372036854775808"), {
				error: "Invalid value: Expected int64 to be >= -9223372036854775808",
			})
			.max(BigInt("9223372036854775807"), {
				error: "Invalid value: Expected int64 to be <= 9223372036854775807",
			}),
	),
});

/**
 * Sandbox content listing
 */
export const zSandboxContentViewWritable = z.object({
	contents: z.optional(z.array(zSandboxContentItemWritable)),
});

export const zSandboxCommandViewWritable = z.object({
	id: z.optional(z.string()),
	command: z.optional(z.string()),
	runtime: z.optional(z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"])),
	status: z.optional(z.enum(["INPROGRESS", "SUCCESSFUL", "FAILED"])),
	exit_code: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	logs_url: z.optional(z.string()),
});

export const zSandboxCommandsViewWritable = z.object({
	commands: z.optional(z.array(zSandboxCommandViewWritable)),
});

export const zSandboxAppLogsViewWritable = z.object({
	cursor: z.optional(z.string()),
	logs: z.optional(z.array(z.string())),
});

export const zShortSnapshotViewWritable = z.object({
	id: z.optional(z.string()),
	name: z.optional(z.string()),
	size: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	status: z.optional(z.enum(["CREATING", "CREATED", "DELETING", "FAILED"])),
	create_date: z.optional(z.iso.datetime()),
});

export const zSnapshotsViewWritable = z.object({
	snapshots: z.optional(z.array(zShortSnapshotViewWritable)),
});

export const zSnapshotViewWritable = z.object({
	id: z.optional(z.string()),
	name: z.optional(z.string()),
	size: z.optional(
		z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	),
	status: z.optional(z.enum(["CREATING", "CREATED", "DELETING", "FAILED"])),
	create_date: z.optional(z.iso.datetime()),
	created_by: z.optional(zMemberViewWritable),
});

export const zSandboxYamlViewWritable = z.object({
	yaml: z.optional(z.string()),
});

export const zCreateNewSandboxRequestWritable = z.object({
	name: z.string(),
	identifier: z.optional(z.string()),
	os: z.string(),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelViewWritable)),
	variables: z.optional(z.array(zAddVariableInObjectRequestWritable)),
});

export const zCreateFromSnapshotRequestWritable = z.object({
	snapshot_id: z.string(),
	name: z.string(),
	identifier: z.optional(z.string()),
	os: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	endpoints: z.optional(z.array(zTunnelViewWritable)),
	variables: z.optional(z.array(zEnvironmentVariableView)),
});

export const zSandboxResponseWritable = z.object({
	id: z.optional(z.string()),
	identifier: z.optional(z.string()),
	name: z.optional(z.string()),
	status: z.optional(
		z.enum([
			"STARTING",
			"STOPPING",
			"FAILED",
			"RUNNING",
			"STOPPED",
			"RESTORING",
		]),
	),
	os: z.optional(z.string()),
	resources: z.optional(
		z.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		]),
	),
	install_commands: z.optional(z.string()),
	run_command: z.optional(z.string()),
	app_dir: z.optional(z.string()),
	app_type: z.optional(z.enum(["CMD", "SERVICE"])),
	tags: z.optional(z.array(z.string())),
	app_status: z.optional(z.enum(["NONE", "RUNNING", "ENDED", "FAILED"])),
	boot_logs: z.optional(z.array(z.string())),
	setup_status: z.optional(z.enum(["INPROGRESS", "SUCCESS", "FAILED"])),
	endpoints: z.optional(z.array(zTunnelViewWritable)),
	project: z.optional(zProjectViewWritable),
	permissions: z.optional(zPermissionsView),
	variables: z.optional(z.array(zEnvironmentVariableView)),
});

export const zProjectsViewWritable = z.object({
	projects: z.optional(z.array(zShortProjectViewWritable)),
});

export const zGetWorkspacesData = z.object({
	body: z.optional(z.never()),
	path: z.optional(z.never()),
	query: z.optional(z.never()),
});

export const zGetWorkspacesResponse = zWorkspacesView;

export const zGetWorkspaceData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetWorkspaceResponse = zWorkspaceView;

export const zDisableSsoData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zEnableSsoData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetIdentifiersData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(
		z.object({
			project: z.optional(z.string()),
			pipeline: z.optional(z.string()),
			environment: z.optional(z.string()),
			package: z.optional(z.string()),
			package_version: z.optional(z.string()),
			sandbox: z.optional(z.string()),
		}),
	),
});

export const zGetIdentifiersResponse = zIdsView;

export const zGetIntegrationsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetIntegrationsResponse = zIntegrationsView;

export const zAddIntegrationData = z.object({
	body: z.optional(zAddIntegrationRequest),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zAddIntegrationResponse = zIntegrationView;

export const zDeleteIntegrationData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		hash_id: z.string(),
	}),
	query: z.optional(z.never()),
});

/**
 * Integration deleted successfully
 */
export const zDeleteIntegrationResponse = z.void();

export const zGetIntegrationData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		hash_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetIntegrationResponse = zIntegrationView;

export const zUpdateIntegrationData = z.object({
	body: z.optional(zUpdateIntegrationRequest),
	path: z.object({
		workspace_domain: z.string(),
		hash_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zUpdateIntegrationResponse = zIntegrationView;

export const zGetWorkspaceMembersData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(
		z.object({
			page: z.optional(
				z
					.int()
					.min(-2147483648, {
						error: "Invalid value: Expected int32 to be >= -2147483648",
					})
					.max(2147483647, {
						error: "Invalid value: Expected int32 to be <= 2147483647",
					}),
			),
			per_page: z.optional(
				z
					.int()
					.min(-2147483648, {
						error: "Invalid value: Expected int32 to be >= -2147483648",
					})
					.max(2147483647, {
						error: "Invalid value: Expected int32 to be <= 2147483647",
					}),
			),
			sort_by: z.optional(z.string()),
			sort_direction: z.optional(z.string()),
		}),
	),
});

export const zGetWorkspaceMembersResponse = zWorkspaceMembersView;

export const zAddWorkspaceMemberData = z.object({
	body: z.optional(zAddWorkspaceMemberRequest),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zAddWorkspaceMemberResponse = zWorkspaceMemberView;

export const zDeleteWorkspaceMemberData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		id: z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	}),
	query: z.optional(z.never()),
});

/**
 * Workspace member deleted successfully
 */
export const zDeleteWorkspaceMemberResponse = z.void();

export const zGetWorkspaceMemberData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		id: z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	}),
	query: z.optional(z.never()),
});

export const zGetWorkspaceMemberResponse = zWorkspaceMemberView;

export const zUpdateWorkspaceMemberData = z.object({
	body: z.optional(zUpdateWorkspaceMemberRequest),
	path: z.object({
		workspace_domain: z.string(),
		id: z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	}),
	query: z.optional(z.never()),
});

export const zUpdateWorkspaceMemberResponse = zWorkspaceMemberView;

export const zGetWorkspaceMemberProjectsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		user_id: z
			.int()
			.min(-2147483648, {
				error: "Invalid value: Expected int32 to be >= -2147483648",
			})
			.max(2147483647, {
				error: "Invalid value: Expected int32 to be <= 2147483647",
			}),
	}),
	query: z.optional(
		z.object({
			page: z.optional(
				z
					.int()
					.min(-2147483648, {
						error: "Invalid value: Expected int32 to be >= -2147483648",
					})
					.max(2147483647, {
						error: "Invalid value: Expected int32 to be <= 2147483647",
					}),
			),
			per_page: z.optional(
				z
					.int()
					.min(-2147483648, {
						error: "Invalid value: Expected int32 to be >= -2147483648",
					})
					.max(2147483647, {
						error: "Invalid value: Expected int32 to be <= 2147483647",
					}),
			),
			status: z.optional(z.string()),
			sort_by: z.optional(z.string()),
			sort_direction: z.optional(z.string()),
			all: z.optional(z.string()),
		}),
	),
});

export const zGetWorkspaceMemberProjectsResponse = zProjectsView;

export const zGetSandboxesData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.object({
		project_name: z.string(),
	}),
});

export const zGetSandboxesResponse = zSandboxesView;

export const zAddSandboxData = z.object({
	body: z.optional(
		z.union([
			zCloneSandboxRequest,
			zCreateFromSnapshotRequestWritable,
			zCreateNewSandboxRequestWritable,
		]),
	),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.object({
		project_name: z.string(),
	}),
});

export const zAddSandboxResponse = zSandboxResponse;

export const zDeleteSandboxData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

/**
 * Sandbox deleted successfully
 */
export const zDeleteSandboxResponse = z.void();

export const zGetSandboxData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxResponse = zSandboxResponse;

export const zUpdateSandboxData = z.object({
	body: z.optional(zUpdateSandboxRequestWritable),
	path: z.object({
		workspace_domain: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zUpdateSandboxResponse = zSandboxResponse;

export const zGetSandboxAppLogsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(
		z.object({
			cursor: z.optional(z.string()),
		}),
	),
});

export const zGetSandboxAppLogsResponse = zSandboxAppLogsView;

export const zGetSandboxCommandsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxCommandsResponse = zSandboxCommandsView;

export const zExecuteSandboxCommandData = z.object({
	body: z.optional(zExecuteSandboxCommandRequest),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zExecuteSandboxCommandResponse = zSandboxCommandView;

export const zGetSandboxCommandData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxCommandResponse = zSandboxCommandView;

export const zGetSandboxCommandLogsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		command_id: z.string(),
	}),
	query: z.optional(
		z.object({
			follow: z.optional(z.boolean()),
		}),
	),
});

export const zGetSandboxCommandLogsResponse = zSandboxCommandLog;

export const zTerminateSandboxCommandData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		command_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zTerminateSandboxCommandResponse = zSandboxCommandView;

export const zDeleteSandboxFileData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		path: z.string().regex(/.*/),
	}),
	query: z.optional(z.never()),
});

/**
 * File or directory deleted successfully
 */
export const zDeleteSandboxFileResponse = z.void();

export const zGetSandboxContentData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		path: z.string().regex(/.*/),
	}),
	query: z.optional(z.never()),
});

/**
 * Content retrieved successfully
 */
export const zGetSandboxContentResponse = zSandboxContentView;

export const zCreateSandboxDirectoryData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		path: z.string().regex(/.*/),
	}),
	query: z.optional(z.never()),
});

/**
 * Directory created successfully
 */
export const zCreateSandboxDirectoryResponse = zSandboxContentItem;

export const zUploadSandboxFileData = z.object({
	body: z.optional(z.string()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		path: z.string().regex(/.*/),
	}),
	query: z.optional(z.never()),
});

/**
 * File uploaded successfully
 */
export const zUploadSandboxFileResponse = zSandboxContentItem;

export const zDownloadSandboxContentData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		path: z.string().regex(/.*/),
	}),
	query: z.optional(z.never()),
});

/**
 * File download
 */
export const zDownloadSandboxContentResponse = z.string();

export const zRestartSandboxData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zRestartSandboxResponse = zSandboxResponse;

export const zGetSandboxSnapshotsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxSnapshotsResponse = zSnapshotsView;

export const zAddSandboxSnapshotData = z.object({
	body: z.optional(zAddSnapshotRequest),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zAddSandboxSnapshotResponse = zSnapshotView;

export const zDeleteSandboxSnapshotData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

/**
 * Sandbox snapshot deleted successfully
 */
export const zDeleteSandboxSnapshotResponse = z.void();

export const zGetSandboxSnapshotData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxSnapshotResponse = zSnapshotView;

export const zStartSandboxData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zStartSandboxResponse = zSandboxResponse;

export const zStopSandboxData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zStopSandboxResponse = zSandboxResponse;

export const zGetSandboxYamlData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSandboxYamlResponse = zSandboxYamlView;

export const zUpdateSandboxByYamlData = z.object({
	body: z.optional(zSandboxYamlViewWritable),
	path: z.object({
		workspace_domain: z.string(),
		sandbox_id: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zUpdateSandboxByYamlResponse = zSandboxResponse;

export const zGetProjectSnapshotsData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.object({
		project_name: z.string(),
	}),
});

export const zGetProjectSnapshotsResponse = zSnapshotsView;

export const zDeleteSnapshotData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
		id: z.string(),
	}),
	query: z.optional(z.never()),
});

/**
 * Sandbox snapshot deleted successfully
 */
export const zDeleteSnapshotResponse = z.void();

export const zAddSandboxByYamlData = z.object({
	body: z.optional(zSandboxYamlViewWritable),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.object({
		project_name: z.string(),
	}),
});

export const zAddSandboxByYamlResponse = zSandboxResponse;

export const zGetSsoData = z.object({
	body: z.optional(z.never()),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zGetSsoResponse = zSsoView;

export const zUpdateSsoData = z.object({
	body: z.optional(zUpdateSsoRequest),
	path: z.object({
		workspace_domain: z.string(),
	}),
	query: z.optional(z.never()),
});

export const zUpdateSsoResponse = zSsoView;
