// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zUpdateWorkspaceMemberRequest = z.object({
	admin: z.boolean().optional(),
	auto_assign_to_new_projects: z.boolean().optional(),
	auto_assign_permission_set_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
});

export const zUpdateSsoRequest = z.object({
	type: z.enum(["SAML", "OIDC"]).optional(),
	sso_provider_type: z
		.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"])
		.optional(),
	sso_url: z.string().optional(),
	issuer: z.string().optional(),
	certificate: z.string().optional(),
	signature_method: z.string().optional(),
	digest_method: z.string().optional(),
	client_id: z.string().optional(),
	client_secret: z.string().optional(),
	require_sso_for_all_members: z.boolean().optional(),
});

export const zGroupPermissionView = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	access_level: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
});

export const zUserPermissionView = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	access_level: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
});

/**
 * Permission settings defining who can use this integration
 */
export const zIntegrationPermissionsView = z.object({
	others: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
	users: z.array(zUserPermissionView).optional(),
	groups: z.array(zGroupPermissionView).optional(),
	admins: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
});

/**
 * Pipeline reference
 */
export const zPipelineIdView = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

export const zRoleAssumptionView = z.object({
	arn: z.string().optional(),
	external_id: z.string().optional(),
	duration: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
});

export const zUpdateIntegrationRequest = z.object({
	identifier: z.string().optional(),
	name: z.string(),
	token: z.string().optional(),
	email: z.string().optional(),
	api_key: z.string().optional(),
	access_key: z.string().optional(),
	secret_key: z.string().optional(),
	partner_token: z.string().optional(),
	shop: z.string().optional(),
	url: z.string().optional(),
	chat_id: z.string().optional(),
	git_hub_user_id: z.string().optional(),
	git_hub_user_name: z.string().optional(),
	username: z.string().optional(),
	password: z.string().optional(),
	app_id: z.string().optional(),
	tenant_id: z.string().optional(),
	client_id: z.string().optional(),
	client_token: z.string().optional(),
	server_id: z.string().optional(),
	server_token: z.string().optional(),
	key_id: z.string().optional(),
	application_key: z.string().optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	slack_user_id: z.string().optional(),
	region: z.string().optional(),
	role_assumptions: z.array(zRoleAssumptionView).optional(),
	all_pipelines_allowed: z.boolean().optional(),
	allowed_pipelines: z.array(zPipelineIdView).optional(),
	permissions: zIntegrationPermissionsView.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	target_url: z.string().optional(),
	refresh_token: z.string().optional(),
	audience: z.string().optional(),
	config: z.string().optional(),
	google_project: z.string().optional(),
	atop_url: z.string().optional(),
	disabled: z.boolean().optional(),
});

export const zShortWorkspaceView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	domain: z.string().optional(),
});

export const zWorkspacesView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	workspaces: z.array(zShortWorkspaceView).optional(),
});

export const zWorkspaceMemberView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	avatar_url: z.string().optional(),
	email: z.string().optional(),
	admin: z.boolean().optional(),
	workspace_owner: z.boolean().optional(),
	auto_assign_to_new_projects: z.boolean().optional(),
	auto_assign_permission_set_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
});

export const zWorkspaceMembersView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	members: z.array(zWorkspaceMemberView).optional(),
});

export const zWorkspaceView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	domain: z.string().optional(),
	owner_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	frozen: z.boolean().optional(),
	create_date: z.iso.datetime().optional(),
	default_pipeline_resource: z
		.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		])
		.optional(),
	sso_enabled: z.boolean().optional(),
	public_pipelines_disabled: z.boolean().optional(),
});

export const zSsoView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	type: z.enum(["SAML", "OIDC"]).optional(),
	sso_provider_type: z
		.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"])
		.optional(),
	sso_url: z.string().optional(),
	issuer: z.string().optional(),
	certificate: z.string().optional(),
	signature_method: z.string().optional(),
	digest_method: z.string().optional(),
	require_sso_for_all_members: z.boolean().optional(),
});

/**
 * YAML pipeline definition configuration
 */
export const zYamlDefinitionView = z.object({
	path: z.string().optional(),
	branch: z.string().optional(),
	project: z.string().optional(),
});

/**
 * The parameters passed to the remote pipeline definition
 */
export const zPipelinePropertyView = z.object({
	key: z.string().optional(),
	value: z.string().optional(),
});

/**
 * Defines how the target can be used (as deployment target, proxy, or both)
 */
export const zUseAsView = z.object({
	target: z.boolean().optional(),
	proxy: z.boolean().optional(),
});

/**
 * List of specific sandboxes allowed to use this target
 */
export const zAllowedSandboxView = z.object({
	project: z.string(),
	sandbox: z.string(),
	access_level: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
});

/**
 * List of specific pipelines allowed to use this target
 */
export const zAllowedPipelineView = z.object({
	project: z.string(),
	pipeline: z.string(),
	access_level: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
});

/**
 * Access permissions configuration
 */
export const zPermissionsView = z.object({
	others: z
		.enum([
			"DENIED",
			"READ_ONLY",
			"USE_ONLY",
			"BLIND",
			"RUN_ONLY",
			"READ_WRITE",
			"MANAGE",
			"DEFAULT",
			"ALLOWED",
			"STAGE",
			"COMMIT",
		])
		.optional(),
	users: z.array(zUserPermissionView).optional(),
	groups: z.array(zGroupPermissionView).optional(),
});

/**
 * Short representation of an environment object
 */
export const zShortEnvironmentView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	name: z.string().optional(),
	identifier: z.string().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	scope: z.enum(["PROJECT", "WORKSPACE", "ANY"]).optional(),
});

export const zPipelineEnvironmentContextView = z.object({
	identifier: z.string().optional(),
	tags: z.array(z.string()).optional(),
	scope: z.enum(["PROJECT", "WORKSPACE", "ANY"]).optional(),
});

export const zPipelineArtifactContextView = z.object({
	identifier: z.string().optional(),
	scope: z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT", "ANY"]).optional(),
});

/**
 * Short representation of a project
 */
export const zShortProjectView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	name: z.string().optional(),
	display_name: z.string(),
	status: z.string().optional(),
	access: z.enum(["PRIVATE", "PUBLIC"]).optional(),
	create_date: z.iso.datetime().optional(),
});

/**
 * MSSQL authentication credentials
 */
export const zMssqlAuthView = z.object({
	method: z.enum(["PASSWORD"]).optional(),
	username: z.string(),
	password: z.string(),
});

/**
 * MongoDB authentication credentials
 */
export const zMongoAuthView = z.object({
	method: z.enum(["PASSWORD"]).optional(),
	username: z.string(),
	password: z.string(),
});

/**
 * PostgreSQL authentication credentials
 */
export const zPostgresqlAuthView = z.object({
	method: z.enum(["PASSWORD"]).optional(),
	username: z.string(),
	password: z.string(),
});

/**
 * MySQL authentication credentials
 */
export const zMysqlAuthView = z.object({
	method: z.enum(["PASSWORD"]).optional(),
	username: z.string(),
	password: z.string(),
});

/**
 * Define proxy servers' authentication method using the following parameters
 */
export const zSshAuthView = z.object({
	method: z.enum([
		"PASSWORD",
		"SSH_KEY",
		"ASSETS_KEY",
		"PROXY_CREDENTIALS",
		"PROXY_KEY",
	]),
	username: z.string().optional(),
	password: z.string().optional(),
	asset: z.string().optional(),
	passphrase: z.string().optional(),
	key: z.string().optional(),
	key_path: z.string().optional(),
});

/**
 * Kubernetes cluster authentication method
 */
export const zK8sAuthView = z.object({
	method: z.enum(["PASS", "CERT", "TOKEN"]),
	username: z.string().optional(),
	password: z.string().optional(),
	certificate_authority: z.string().optional(),
	client_certificate: z.string().optional(),
	client_key: z.string().optional(),
	token: z.string().optional(),
});

/**
 * Authentication details
 */
export const zGitAuthView = z.object({
	method: z.enum(["HTTP", "SSH_KEY", "ASSETS_KEY", "CURRENT"]),
	username: z.string().optional(),
	password: z.string().optional(),
	asset: z.string().optional(),
	key: z.string().optional(),
});

/**
 * Authentication details
 */
export const zFtpAuthView = z.object({
	username: z.string(),
	password: z.string(),
});

export const zIdsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	domain: z.string().optional(),
	project_identifier: z.string().optional(),
	pipeline_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	environment_id: z.string().optional(),
	artifact_id: z.string().optional(),
	artifact_version_id: z.string().optional(),
	sandbox_id: z.string().optional(),
	unit_test_suite_id: z.string().optional(),
	visual_test_suite_id: z.string().optional(),
	crawl_suite_id: z.string().optional(),
	distribution_id: z.string().optional(),
	route_id: z.string().optional(),
});

export const zAddWorkspaceMemberRequest = z.object({
	admin: z.boolean().optional(),
	auto_assign_to_new_projects: z.boolean().optional(),
	auto_assign_permission_set_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	email: z.string(),
});

export const zAddIntegrationRequest = z.object({
	identifier: z.string().optional(),
	name: z.string(),
	token: z.string().optional(),
	email: z.string().optional(),
	api_key: z.string().optional(),
	access_key: z.string().optional(),
	secret_key: z.string().optional(),
	partner_token: z.string().optional(),
	shop: z.string().optional(),
	url: z.string().optional(),
	chat_id: z.string().optional(),
	git_hub_user_id: z.string().optional(),
	git_hub_user_name: z.string().optional(),
	username: z.string().optional(),
	password: z.string().optional(),
	app_id: z.string().optional(),
	tenant_id: z.string().optional(),
	client_id: z.string().optional(),
	client_token: z.string().optional(),
	server_id: z.string().optional(),
	server_token: z.string().optional(),
	key_id: z.string().optional(),
	application_key: z.string().optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	slack_user_id: z.string().optional(),
	region: z.string().optional(),
	role_assumptions: z.array(zRoleAssumptionView).optional(),
	all_pipelines_allowed: z.boolean().optional(),
	allowed_pipelines: z.array(zPipelineIdView).optional(),
	permissions: zIntegrationPermissionsView.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	target_url: z.string().optional(),
	refresh_token: z.string().optional(),
	audience: z.string().optional(),
	config: z.string().optional(),
	google_project: z.string().optional(),
	atop_url: z.string().optional(),
	disabled: z.boolean().optional(),
	type: z.enum([
		"GIT_HUB",
		"BITBUCKET",
		"GOOGLE",
		"DIGITAL_OCEAN",
		"SLACK",
		"MODULUS",
		"HEROKU",
		"AMAZON",
		"GIT_LAB",
		"SHOPIFY",
		"GIT_HUB_ENTERPRISE",
		"GIT_LAB_ENTERPRISE",
		"PUSHOVER",
		"PUSHBULLET",
		"RACKSPACE",
		"CUSTOM",
		"CLOUDFLARE",
		"NEW_RELIC",
		"SENTRY",
		"ROLLBAR",
		"DATADOG",
		"DO_SPACES",
		"HONEYBADGER",
		"VULTR",
		"SENTRY_ENTERPRISE",
		"LOGGLY",
		"HIP_CHAT",
		"FIREBASE",
		"TELEGRAM",
		"AZURE",
		"UPCLOUD",
		"GHOST_INSPECTOR",
		"NETLIFY",
		"AZURE_CLOUD",
		"MICROSOFT_TEAMS",
		"GOOGLE_SERVICE_ACCOUNT",
		"GOOGLE_PLAY_STORE",
		"DOCKER_HUB",
		"APP_STORE",
		"GIT_HUB_APP",
		"GIT_HUB_APP_ENTERPRISE",
		"GIT_HUB_API",
		"ATOP",
		"SNYK",
		"STACK_HAWK",
		"BLACKFIRE",
		"BACKBLAZE",
		"ONE_LOGIN",
		"OKTA",
		"CONTENTFUL",
		"JIRA",
		"NPM_REGISTRY",
		"ANTHROPIC",
	]),
	scope: z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"]),
	project_name: z.string().optional(),
});

/**
 * Sandbox reference
 */
export const zSandboxIdView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z.string().optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	status: z
		.enum(["STARTING", "STOPPING", "FAILED", "RUNNING", "STOPPED", "RESTORING"])
		.optional(),
	setup_status: z.enum(["INPROGRESS", "SUCCESS", "FAILED"]).optional(),
});

/**
 * Integration reference
 */
export const zIntegrationIdView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	identifier: z.string().optional(),
	hash_id: z.string().optional(),
	name: z.string().optional(),
	type: z
		.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
			"JIRA",
			"NPM_REGISTRY",
			"ANTHROPIC",
		])
		.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	atop_url: z.string().optional(),
	app_id: z.string().optional(),
	google_project: z.string().optional(),
	audience: z.string().optional(),
});

/**
 * User/member reference
 */
export const zMemberView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	avatar_url: z.string().optional(),
	email: z.string().optional(),
	admin: z.boolean().optional(),
	workspace_owner: z.boolean().optional(),
});

export const zProjectView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	name: z.string().optional(),
	display_name: z.string(),
	status: z.string().optional(),
	access: z.enum(["PRIVATE", "PUBLIC"]).optional(),
	create_date: z.iso.datetime().optional(),
	external_project_id: z.string().optional(),
	git_lab_project_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	custom_repo_url: z.string().optional(),
	custom_repo_user: z.string().optional(),
	custom_repo_pass: z.string().optional(),
	custom_repo_ssh_key_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	created_by: zMemberView.optional(),
	http_repository: z.string().optional(),
	ssh_repository: z.string().optional(),
	default_branch: z.string().optional(),
	integration: zIntegrationIdView.optional(),
	fetch_submodules: z.boolean().optional(),
	fetch_submodules_env_key: z.string().optional(),
	allow_pull_requests: z.boolean().optional(),
	update_default_branch_from_external: z.boolean().optional(),
	without_repository: z.boolean().optional(),
});

/**
 * The environment variables of the sandbox
 */
export const zAddVariableInObjectRequest = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	key: z.string(),
	value: z.string().optional(),
	settable: z.boolean().optional(),
	run_only_settable: z.boolean().optional(),
	encrypted: z.boolean().optional(),
	description: z.string().optional(),
	init_path: z.string().optional(),
	defaults: z.string().optional(),
	file_path: z.string().optional(),
	file_chmod: z.string().optional(),
	file_place: z.enum(["NONE", "CONTAINER"]).optional(),
	password: z.string().optional(),
	passphrase: z.string().optional(),
	key_identifier: z.string().optional(),
	disabled: z.boolean().optional(),
	type: z.enum([
		"VAR",
		"FILE",
		"SSH_KEY",
		"IOS_KEYCHAIN",
		"IOS_PROVISION_PROFILES",
		"SSH_PUBLIC_KEY",
		"GPG_KEY",
	]),
});

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export const zTlsSettingsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	terminate_at: z.enum(["REGION", "AGENT", "TARGET"]).optional(),
});

/**
 * The HTTP-specific settings of the tunnel
 */
export const zHttpSettingsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	verify_certificate: z.boolean().optional(),
	compression: z.boolean().optional(),
	http2: z.boolean().optional(),
	log_requests: z.boolean().optional(),
	request_headers: z.record(z.string(), z.string()).optional(),
	whitelist_user_agents: z.array(z.string()).optional(),
	rewrite_host_header: z.string().optional(),
	response_headers: z.record(z.string(), z.string()).optional(),
	login: z.string().optional(),
	circuit_breaker: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	serve_path: z.string().optional(),
	auth_type: z.enum(["NONE", "BASIC", "BUDDY"]).optional(),
});

export const zTunnelView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	name: z.string(),
	endpoint: z.string(),
	type: z.enum(["TCP", "TLS", "HTTP", "SSH"]),
	region: z.enum(["US", "EU", "AS"]),
	whitelist: z.array(z.string()).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	http: zHttpSettingsView.optional(),
	tls: zTlsSettingsView.optional(),
	endpoint_url: z.string().optional(),
});

export const zSandboxFetchView = z.object({
	type: z.enum(["PROJECT_REPO", "PUBLIC_REPO", "ARTIFACT"]).optional(),
	repository: z.string().optional(),
	ref: z.string().optional(),
	path: z.string().optional(),
	build_command: z.string().optional(),
	artifact: z.string().optional(),
});

export const zSandboxAppView = z.object({
	id: z.string().optional(),
	command: z.string().optional(),
	app_status: z.enum(["NONE", "RUNNING", "ENDED", "FAILED"]).optional(),
});

export const zUpdateSandboxRequest = z.object({
	name: z.string().optional(),
	identifier: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(zSandboxAppView).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelView).optional(),
	variables: z.array(zAddVariableInObjectRequest).optional(),
	permissions: zPermissionsView.optional(),
});

export const zSandboxesView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	sandboxes: z.array(zSandboxIdView).optional(),
});

/**
 * Content item in a sandbox
 */
export const zSandboxContentItem = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	type: z.enum(["FILE", "DIR"]).optional(),
	name: z.string().optional(),
	path: z.string().optional(),
	size: z.coerce
		.bigint()
		.min(BigInt("-9223372036854775808"), {
			error: "Invalid value: Expected int64 to be >= -9223372036854775808",
		})
		.max(BigInt("9223372036854775807"), {
			error: "Invalid value: Expected int64 to be <= 9223372036854775807",
		})
		.optional(),
});

/**
 * Sandbox content listing
 */
export const zSandboxContentView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	contents: z.array(zSandboxContentItem).optional(),
});

export const zSandboxCommandView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z.string().optional(),
	command: z.string().optional(),
	runtime: z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"]).optional(),
	status: z.enum(["INPROGRESS", "SUCCESSFUL", "FAILED"]).optional(),
	exit_code: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	start_date: z.iso.datetime().optional(),
	finish_date: z.iso.datetime().optional(),
	logs_url: z.string().optional(),
});

export const zSandboxCommandsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	commands: z.array(zSandboxCommandView).optional(),
});

export const zSandboxCommandLog = z.object({
	type: z.enum(["STDOUT", "STDERR"]).optional(),
	data: z.string().optional(),
});

export const zSandboxAppLogsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	cursor: z.string().optional(),
	logs: z.array(z.string()).optional(),
});

export const zShortSnapshotView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z.string().optional(),
	name: z.string().optional(),
	size: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	status: z.enum(["CREATING", "CREATED", "DELETING", "FAILED"]).optional(),
	create_date: z.iso.datetime().optional(),
});

export const zSnapshotsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	snapshots: z.array(zShortSnapshotView).optional(),
});

export const zExecuteSandboxCommandRequest = z.object({
	command: z.string(),
	runtime: z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"]).optional(),
});

export const zAddSnapshotRequest = z.object({
	name: z.string().optional(),
});

export const zSnapshotView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z.string().optional(),
	name: z.string().optional(),
	size: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	status: z.enum(["CREATING", "CREATED", "DELETING", "FAILED"]).optional(),
	create_date: z.iso.datetime().optional(),
	created_by: zMemberView.optional(),
});

export const zSandboxYamlView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	yaml: z.string().optional(),
});

export const zCreateNewSandboxRequest = z.object({
	name: z.string(),
	identifier: z.string().optional(),
	os: z.string(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(z.string()).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelView).optional(),
	variables: z.array(zAddVariableInObjectRequest).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	permissions: zPermissionsView.optional(),
});

export const zEnvironmentVariableView = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	key: z.string().optional(),
	value: z.string().optional(),
	type: z
		.enum([
			"VAR",
			"FILE",
			"SSH_KEY",
			"IOS_KEYCHAIN",
			"IOS_PROVISION_PROFILES",
			"SSH_PUBLIC_KEY",
			"GPG_KEY",
		])
		.optional(),
	encrypted: z.boolean().optional(),
	settable: z.boolean().optional(),
	run_only_settable: z.boolean().optional(),
	description: z.string().optional(),
	init_path: z.string().optional(),
	defaults: z.string().optional(),
	file_path: z.string().optional(),
	file_chmod: z.string().optional(),
	file_place: z.enum(["NONE", "CONTAINER"]).optional(),
	binary: z.boolean().optional(),
	public_value: z.string().optional(),
	key_fingerprint: z.string().optional(),
	checksum: z.string().optional(),
	password: z.string().optional(),
	passphrase: z.string().optional(),
	key_identifier: z.string().optional(),
	disabled: z.boolean().optional(),
});

export const zCreateFromSnapshotRequest = z.object({
	snapshot_id: z.string(),
	name: z.string(),
	identifier: z.string().optional(),
	os: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(z.string()).optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelView).optional(),
	variables: z.array(zEnvironmentVariableView).optional(),
});

export const zCloneSandboxRequest = z.object({
	source_sandbox_id: z.string(),
	name: z.string(),
	identifier: z.string().optional(),
});

export const zSandboxResponse = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z.string().optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	status: z
		.enum(["STARTING", "STOPPING", "FAILED", "RUNNING", "STOPPED", "RESTORING"])
		.optional(),
	setup_status: z.enum(["INPROGRESS", "SUCCESS", "FAILED", "STALE"]).optional(),
	os: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(zSandboxAppView).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	tags: z.array(z.string()).optional(),
	boot_logs: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelView).optional(),
	ssh_host: z.string().optional(),
	ssh_port: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	project: zProjectView.optional(),
	permissions: zPermissionsView.optional(),
	variables: z.array(zEnvironmentVariableView).optional(),
});

export const zProjectsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	projects: z.array(zShortProjectView).optional(),
});

export const zShortWorkspaceViewWritable = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	domain: z.string().optional(),
});

export const zWorkspacesViewWritable = z.object({
	workspaces: z.array(zShortWorkspaceViewWritable).optional(),
});

export const zWorkspaceMemberViewWritable = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	avatar_url: z.string().optional(),
	email: z.string().optional(),
	admin: z.boolean().optional(),
	workspace_owner: z.boolean().optional(),
	auto_assign_to_new_projects: z.boolean().optional(),
	auto_assign_permission_set_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
});

export const zWorkspaceMembersViewWritable = z.object({
	members: z.array(zWorkspaceMemberViewWritable).optional(),
});

export const zWorkspaceViewWritable = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	domain: z.string().optional(),
	owner_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	frozen: z.boolean().optional(),
	create_date: z.iso.datetime().optional(),
	default_pipeline_resource: z
		.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		])
		.optional(),
	sso_enabled: z.boolean().optional(),
	public_pipelines_disabled: z.boolean().optional(),
});

export const zSsoViewWritable = z.object({
	type: z.enum(["SAML", "OIDC"]).optional(),
	sso_provider_type: z
		.enum(["OKTA", "ONE_LOGIN", "GOOGLE", "AZURE", "AWS", "CUSTOM"])
		.optional(),
	sso_url: z.string().optional(),
	issuer: z.string().optional(),
	certificate: z.string().optional(),
	signature_method: z.string().optional(),
	digest_method: z.string().optional(),
	require_sso_for_all_members: z.boolean().optional(),
});

/**
 * Short representation of an environment object
 */
export const zShortEnvironmentViewWritable = z.object({
	name: z.string().optional(),
	identifier: z.string().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	scope: z.enum(["PROJECT", "WORKSPACE", "ANY"]).optional(),
});

/**
 * Short representation of a project
 */
export const zShortProjectViewWritable = z.object({
	name: z.string().optional(),
	display_name: z.string(),
	status: z.string().optional(),
	access: z.enum(["PRIVATE", "PUBLIC"]).optional(),
	create_date: z.iso.datetime().optional(),
});

export const zIdsViewWritable = z.object({
	domain: z.string().optional(),
	project_identifier: z.string().optional(),
	pipeline_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	environment_id: z.string().optional(),
	artifact_id: z.string().optional(),
	artifact_version_id: z.string().optional(),
	sandbox_id: z.string().optional(),
	unit_test_suite_id: z.string().optional(),
	visual_test_suite_id: z.string().optional(),
	crawl_suite_id: z.string().optional(),
	distribution_id: z.string().optional(),
	route_id: z.string().optional(),
});

/**
 * Sandbox reference
 */
export const zSandboxIdViewWritable = z.object({
	id: z.string().optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	status: z
		.enum(["STARTING", "STOPPING", "FAILED", "RUNNING", "STOPPED", "RESTORING"])
		.optional(),
	setup_status: z.enum(["INPROGRESS", "SUCCESS", "FAILED"]).optional(),
});

/**
 * Integration reference
 */
export const zIntegrationIdViewWritable = z.object({
	identifier: z.string().optional(),
	hash_id: z.string().optional(),
	name: z.string().optional(),
	type: z
		.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
			"JIRA",
			"NPM_REGISTRY",
			"ANTHROPIC",
		])
		.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	atop_url: z.string().optional(),
	app_id: z.string().optional(),
	google_project: z.string().optional(),
	audience: z.string().optional(),
});

/**
 * User/member reference
 */
export const zMemberViewWritable = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	name: z.string().optional(),
	avatar_url: z.string().optional(),
	email: z.string().optional(),
	admin: z.boolean().optional(),
	workspace_owner: z.boolean().optional(),
});

export const zProjectViewWritable = z.object({
	name: z.string().optional(),
	display_name: z.string(),
	status: z.string().optional(),
	access: z.enum(["PRIVATE", "PUBLIC"]).optional(),
	create_date: z.iso.datetime().optional(),
	external_project_id: z.string().optional(),
	git_lab_project_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	custom_repo_url: z.string().optional(),
	custom_repo_user: z.string().optional(),
	custom_repo_pass: z.string().optional(),
	custom_repo_ssh_key_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	created_by: zMemberViewWritable.optional(),
	http_repository: z.string().optional(),
	ssh_repository: z.string().optional(),
	default_branch: z.string().optional(),
	integration: zIntegrationIdViewWritable.optional(),
	fetch_submodules: z.boolean().optional(),
	fetch_submodules_env_key: z.string().optional(),
	allow_pull_requests: z.boolean().optional(),
	update_default_branch_from_external: z.boolean().optional(),
	without_repository: z.boolean().optional(),
});

/**
 * The environment variables of the sandbox
 */
export const zAddVariableInObjectRequestWritable = z.object({
	key: z.string(),
	value: z.string().optional(),
	settable: z.boolean().optional(),
	run_only_settable: z.boolean().optional(),
	encrypted: z.boolean().optional(),
	description: z.string().optional(),
	init_path: z.string().optional(),
	defaults: z.string().optional(),
	file_path: z.string().optional(),
	file_chmod: z.string().optional(),
	file_place: z.enum(["NONE", "CONTAINER"]).optional(),
	password: z.string().optional(),
	passphrase: z.string().optional(),
	key_identifier: z.string().optional(),
	disabled: z.boolean().optional(),
	type: z.enum([
		"VAR",
		"FILE",
		"SSH_KEY",
		"IOS_KEYCHAIN",
		"IOS_PROVISION_PROFILES",
		"SSH_PUBLIC_KEY",
		"GPG_KEY",
	]),
});

/**
 * The TLS/SSL encryption settings of the tunnel
 */
export const zTlsSettingsViewWritable = z.object({
	private_key: z.string().optional(),
	certificate: z.string().optional(),
	ca_certificate: z.string().optional(),
	terminate_at: z.enum(["REGION", "AGENT", "TARGET"]).optional(),
});

/**
 * The HTTP-specific settings of the tunnel
 */
export const zHttpSettingsViewWritable = z.object({
	verify_certificate: z.boolean().optional(),
	compression: z.boolean().optional(),
	http2: z.boolean().optional(),
	log_requests: z.boolean().optional(),
	request_headers: z.record(z.string(), z.string()).optional(),
	whitelist_user_agents: z.array(z.string()).optional(),
	rewrite_host_header: z.string().optional(),
	response_headers: z.record(z.string(), z.string()).optional(),
	login: z.string().optional(),
	password: z.string().optional(),
	tls_ca: z.string().optional(),
	circuit_breaker: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	serve_path: z.string().optional(),
	auth_type: z.enum(["NONE", "BASIC", "BUDDY"]).optional(),
});

export const zTunnelViewWritable = z.object({
	name: z.string(),
	endpoint: z.string(),
	type: z.enum(["TCP", "TLS", "HTTP", "SSH"]),
	region: z.enum(["US", "EU", "AS"]),
	whitelist: z.array(z.string()).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	http: zHttpSettingsViewWritable.optional(),
	tls: zTlsSettingsViewWritable.optional(),
	endpoint_url: z.string().optional(),
});

export const zUpdateSandboxRequestWritable = z.object({
	name: z.string().optional(),
	identifier: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(zSandboxAppView).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelViewWritable).optional(),
	variables: z.array(zAddVariableInObjectRequestWritable).optional(),
	permissions: zPermissionsView.optional(),
});

export const zSandboxesViewWritable = z.object({
	sandboxes: z.array(zSandboxIdViewWritable).optional(),
});

/**
 * Content item in a sandbox
 */
export const zSandboxContentItemWritable = z.object({
	type: z.enum(["FILE", "DIR"]).optional(),
	name: z.string().optional(),
	path: z.string().optional(),
	size: z.coerce
		.bigint()
		.min(BigInt("-9223372036854775808"), {
			error: "Invalid value: Expected int64 to be >= -9223372036854775808",
		})
		.max(BigInt("9223372036854775807"), {
			error: "Invalid value: Expected int64 to be <= 9223372036854775807",
		})
		.optional(),
});

/**
 * Sandbox content listing
 */
export const zSandboxContentViewWritable = z.object({
	contents: z.array(zSandboxContentItemWritable).optional(),
});

export const zSandboxCommandViewWritable = z.object({
	id: z.string().optional(),
	command: z.string().optional(),
	runtime: z.enum(["BASH", "JAVASCRIPT", "TYPESCRIPT", "PYTHON"]).optional(),
	status: z.enum(["INPROGRESS", "SUCCESSFUL", "FAILED"]).optional(),
	exit_code: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	start_date: z.iso.datetime().optional(),
	finish_date: z.iso.datetime().optional(),
	logs_url: z.string().optional(),
});

export const zSandboxCommandsViewWritable = z.object({
	commands: z.array(zSandboxCommandViewWritable).optional(),
});

export const zSandboxAppLogsViewWritable = z.object({
	cursor: z.string().optional(),
	logs: z.array(z.string()).optional(),
});

export const zShortSnapshotViewWritable = z.object({
	id: z.string().optional(),
	name: z.string().optional(),
	size: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	status: z.enum(["CREATING", "CREATED", "DELETING", "FAILED"]).optional(),
	create_date: z.iso.datetime().optional(),
});

export const zSnapshotsViewWritable = z.object({
	snapshots: z.array(zShortSnapshotViewWritable).optional(),
});

export const zSnapshotViewWritable = z.object({
	id: z.string().optional(),
	name: z.string().optional(),
	size: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	status: z.enum(["CREATING", "CREATED", "DELETING", "FAILED"]).optional(),
	create_date: z.iso.datetime().optional(),
	created_by: zMemberViewWritable.optional(),
});

export const zSandboxYamlViewWritable = z.object({
	yaml: z.string().optional(),
});

export const zCreateNewSandboxRequestWritable = z.object({
	name: z.string(),
	identifier: z.string().optional(),
	os: z.string(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(z.string()).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelViewWritable).optional(),
	variables: z.array(zAddVariableInObjectRequestWritable).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	permissions: zPermissionsView.optional(),
});

export const zCreateFromSnapshotRequestWritable = z.object({
	snapshot_id: z.string(),
	name: z.string(),
	identifier: z.string().optional(),
	os: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(z.string()).optional(),
	tags: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelViewWritable).optional(),
	variables: z.array(zEnvironmentVariableView).optional(),
});

export const zSandboxResponseWritable = z.object({
	id: z.string().optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	status: z
		.enum(["STARTING", "STOPPING", "FAILED", "RUNNING", "STOPPED", "RESTORING"])
		.optional(),
	setup_status: z.enum(["INPROGRESS", "SUCCESS", "FAILED", "STALE"]).optional(),
	os: z.string().optional(),
	resources: z
		.enum([
			"1x2",
			"2x4",
			"3x6",
			"4x8",
			"5x10",
			"6x12",
			"7x14",
			"8x16",
			"9x18",
			"10x20",
			"11x22",
			"12x24",
			"CUSTOM",
		])
		.optional(),
	first_boot_commands: z.string().optional(),
	app_dir: z.string().optional(),
	apps: z.array(zSandboxAppView).optional(),
	fetch: z.array(zSandboxFetchView).optional(),
	timeout: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	tags: z.array(z.string()).optional(),
	boot_logs: z.array(z.string()).optional(),
	endpoints: z.array(zTunnelViewWritable).optional(),
	ssh_host: z.string().optional(),
	ssh_port: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	project: zProjectViewWritable.optional(),
	permissions: zPermissionsView.optional(),
	variables: z.array(zEnvironmentVariableView).optional(),
});

export const zProjectsViewWritable = z.object({
	projects: z.array(zShortProjectViewWritable).optional(),
});

export const zIntegrationsView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	integrations: z.array(z.lazy((): any => zIntegrationView)).optional(),
});

/**
 * The list of events that trigger the pipeline run
 */
export const zPipelineEventView = z.object({
	type: z
		.enum([
			"PUSH",
			"CREATE_REF",
			"DELETE_REF",
			"PULL_REQUEST",
			"SCHEDULE",
			"PUBLISH_ARTIFACT_VERSION",
			"DELETE_ARTIFACT_VERSION",
			"WEBHOOK",
			"EMAIL",
			"CREATE_ARTIFACT_VERSION",
			"ENVIRONMENT_CREATE",
			"ENVIRONMENT_DELETE",
			"SANDBOX_CREATED",
			"SANDBOX_DELETED",
			"SANDBOX_TIMED_OUT",
		])
		.optional(),
	refs: z.array(z.string()).optional(),
	events: z.array(z.string()).optional(),
	branches: z.array(z.string()).optional(),
	artifacts: z.array(zPipelineArtifactContextView).optional(),
	environments: z.array(zPipelineEnvironmentContextView).optional(),
	start_date: z.iso.datetime().optional(),
	delay: z.coerce
		.bigint()
		.min(BigInt("-9223372036854775808"), {
			error: "Invalid value: Expected int64 to be >= -9223372036854775808",
		})
		.max(BigInt("9223372036854775807"), {
			error: "Invalid value: Expected int64 to be <= 9223372036854775807",
		})
		.optional(),
	cron: z.string().optional(),
	timezone: z.string().optional(),
	totp: z.boolean().optional(),
	prefix: z.string().optional(),
	whitelist: z.array(z.string()).optional(),
	targets: z.array(z.unknown()).optional(),
});

/**
 * Short representation of a pipeline
 */
export const zShortPipelineView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	definition_source: z.enum(["LOCAL", "REMOTE"]).optional(),
	git_config_ref: z.enum(["NONE", "DYNAMIC", "FIXED"]).optional(),
	refs: z.array(z.string()).optional(),
	events: z.array(zPipelineEventView).optional(),
	loop: z.array(z.string()).optional(),
	priority: z.enum(["LOW", "NORMAL", "HIGH"]).optional(),
	disabled: z.boolean().optional(),
	disabled_reason: z.string().optional(),
	last_execution_status: z
		.enum([
			"INPROGRESS",
			"ENQUEUED",
			"TERMINATED",
			"SUCCESSFUL",
			"FAILED",
			"INITIAL",
			"NOT_EXECUTED",
			"SKIPPED",
			"TERMINATING",
			"WAITING_FOR_APPLY",
			"WAITING_FOR_VARIABLES",
			"WAITING_FOR_SETTABLE_VARIABLES",
			"WAITING_FOR_VT_SESSION",
		])
		.optional(),
	last_execution_revision: z.string().optional(),
	target_site_url: z.string().optional(),
	execution_message_template: z.string().optional(),
	create_date: z.iso.datetime().optional(),
	always_from_scratch: z.boolean().optional(),
	ignore_fail_on_project_status: z.boolean().optional(),
	no_skip_to_most_recent: z.boolean().optional(),
	terminate_stale_runs: z.boolean().optional(),
	auto_clear_cache: z.boolean().optional(),
	paused: z.boolean().optional(),
	pause_on_repeated_failures: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	fetch_all_refs: z.boolean().optional(),
	fetch_lfs: z.boolean().optional(),
	fail_on_prepare_env_warning: z.boolean().optional(),
	concurrent_pipeline_runs: z.boolean().optional(),
	clone_depth: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	do_not_create_commit_status: z.boolean().optional(),
	stale: z.boolean().optional(),
	waiting_for_push: z.boolean().optional(),
	resources: z
		.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		])
		.optional(),
	remote_path: z.string().optional(),
	remote_ref: z.string().optional(),
	remote_project_name: z.string().optional(),
	remote_parameters: z.array(zPipelinePropertyView).optional(),
	git_config: zYamlDefinitionView.optional(),
	tags: z.array(z.string()).optional(),
	git_changeset_base: z
		.enum(["LATEST_RUN", "LATEST_RUN_MATCHING_REF", "PULL_REQUEST"])
		.optional(),
	filesystem_changeset_base: z.enum(["DATE_MODIFIED", "CONTENTS"]).optional(),
	cpu: z.enum(["X64", "ARM", "X86"]).optional(),
	description_required: z.boolean().optional(),
	folder: z.string().optional(),
});

/**
 * The integration to use for authentication
 */
export const zIntegrationView = z.object({
	url: z.string().readonly().optional(),
	html_url: z.string().readonly().optional(),
	identifier: z.string().optional(),
	hash_id: z.string().optional(),
	name: z.string().optional(),
	type: z
		.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
			"JIRA",
			"NPM_REGISTRY",
			"ANTHROPIC",
		])
		.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	scope: z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"]).optional(),
	project_name: z.string().optional(),
	app_id: z.string().optional(),
	google_project: z.string().optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	audience: z.string().optional(),
	atop_url: z.string().optional(),
	permissions: zIntegrationPermissionsView.optional(),
	all_pipelines_allowed: z.boolean().optional(),
	allowed_pipelines: z.array(zShortPipelineView).optional(),
	disabled: z.boolean().optional(),
});

export const zIntegrationsViewWritable = z.object({
	integrations: z.array(z.lazy((): any => zIntegrationViewWritable)).optional(),
});

/**
 * The list of events that trigger the pipeline run
 */
export const zPipelineEventViewWritable = z.object({
	type: z
		.enum([
			"PUSH",
			"CREATE_REF",
			"DELETE_REF",
			"PULL_REQUEST",
			"SCHEDULE",
			"PUBLISH_ARTIFACT_VERSION",
			"DELETE_ARTIFACT_VERSION",
			"WEBHOOK",
			"EMAIL",
			"CREATE_ARTIFACT_VERSION",
			"ENVIRONMENT_CREATE",
			"ENVIRONMENT_DELETE",
			"SANDBOX_CREATED",
			"SANDBOX_DELETED",
			"SANDBOX_TIMED_OUT",
		])
		.optional(),
	refs: z.array(z.string()).optional(),
	events: z.array(z.string()).optional(),
	branches: z.array(z.string()).optional(),
	artifacts: z.array(zPipelineArtifactContextView).optional(),
	environments: z.array(zPipelineEnvironmentContextView).optional(),
	start_date: z.iso.datetime().optional(),
	delay: z.coerce
		.bigint()
		.min(BigInt("-9223372036854775808"), {
			error: "Invalid value: Expected int64 to be >= -9223372036854775808",
		})
		.max(BigInt("9223372036854775807"), {
			error: "Invalid value: Expected int64 to be <= 9223372036854775807",
		})
		.optional(),
	cron: z.string().optional(),
	timezone: z.string().optional(),
	totp: z.boolean().optional(),
	prefix: z.string().optional(),
	whitelist: z.array(z.string()).optional(),
	targets: z.array(z.unknown()).optional(),
});

/**
 * Short representation of a pipeline
 */
export const zShortPipelineViewWritable = z.object({
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	identifier: z.string().optional(),
	name: z.string().optional(),
	definition_source: z.enum(["LOCAL", "REMOTE"]).optional(),
	git_config_ref: z.enum(["NONE", "DYNAMIC", "FIXED"]).optional(),
	refs: z.array(z.string()).optional(),
	events: z.array(zPipelineEventViewWritable).optional(),
	loop: z.array(z.string()).optional(),
	priority: z.enum(["LOW", "NORMAL", "HIGH"]).optional(),
	disabled: z.boolean().optional(),
	disabled_reason: z.string().optional(),
	last_execution_status: z
		.enum([
			"INPROGRESS",
			"ENQUEUED",
			"TERMINATED",
			"SUCCESSFUL",
			"FAILED",
			"INITIAL",
			"NOT_EXECUTED",
			"SKIPPED",
			"TERMINATING",
			"WAITING_FOR_APPLY",
			"WAITING_FOR_VARIABLES",
			"WAITING_FOR_SETTABLE_VARIABLES",
			"WAITING_FOR_VT_SESSION",
		])
		.optional(),
	last_execution_revision: z.string().optional(),
	target_site_url: z.string().optional(),
	execution_message_template: z.string().optional(),
	create_date: z.iso.datetime().optional(),
	always_from_scratch: z.boolean().optional(),
	ignore_fail_on_project_status: z.boolean().optional(),
	no_skip_to_most_recent: z.boolean().optional(),
	terminate_stale_runs: z.boolean().optional(),
	auto_clear_cache: z.boolean().optional(),
	paused: z.boolean().optional(),
	pause_on_repeated_failures: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	fetch_all_refs: z.boolean().optional(),
	fetch_lfs: z.boolean().optional(),
	fail_on_prepare_env_warning: z.boolean().optional(),
	concurrent_pipeline_runs: z.boolean().optional(),
	clone_depth: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	do_not_create_commit_status: z.boolean().optional(),
	stale: z.boolean().optional(),
	waiting_for_push: z.boolean().optional(),
	resources: z
		.enum([
			"DEFAULT",
			"NANO",
			"SMALL",
			"MEDIUM",
			"LARGE",
			"XLARGE",
			"CUSTOM",
			"X2LARGE",
		])
		.optional(),
	remote_path: z.string().optional(),
	remote_ref: z.string().optional(),
	remote_project_name: z.string().optional(),
	remote_parameters: z.array(zPipelinePropertyView).optional(),
	git_config: zYamlDefinitionView.optional(),
	tags: z.array(z.string()).optional(),
	git_changeset_base: z
		.enum(["LATEST_RUN", "LATEST_RUN_MATCHING_REF", "PULL_REQUEST"])
		.optional(),
	filesystem_changeset_base: z.enum(["DATE_MODIFIED", "CONTENTS"]).optional(),
	cpu: z.enum(["X64", "ARM", "X86"]).optional(),
	description_required: z.boolean().optional(),
	folder: z.string().optional(),
});

/**
 * The integration to use for authentication
 */
export const zIntegrationViewWritable = z.object({
	identifier: z.string().optional(),
	hash_id: z.string().optional(),
	name: z.string().optional(),
	type: z
		.enum([
			"GIT_HUB",
			"BITBUCKET",
			"GOOGLE",
			"DIGITAL_OCEAN",
			"SLACK",
			"MODULUS",
			"HEROKU",
			"AMAZON",
			"GIT_LAB",
			"SHOPIFY",
			"GIT_HUB_ENTERPRISE",
			"GIT_LAB_ENTERPRISE",
			"PUSHOVER",
			"PUSHBULLET",
			"RACKSPACE",
			"CUSTOM",
			"CLOUDFLARE",
			"NEW_RELIC",
			"SENTRY",
			"ROLLBAR",
			"DATADOG",
			"DO_SPACES",
			"HONEYBADGER",
			"VULTR",
			"SENTRY_ENTERPRISE",
			"LOGGLY",
			"HIP_CHAT",
			"FIREBASE",
			"TELEGRAM",
			"AZURE",
			"UPCLOUD",
			"GHOST_INSPECTOR",
			"NETLIFY",
			"AZURE_CLOUD",
			"MICROSOFT_TEAMS",
			"GOOGLE_SERVICE_ACCOUNT",
			"GOOGLE_PLAY_STORE",
			"DOCKER_HUB",
			"APP_STORE",
			"GIT_HUB_APP",
			"GIT_HUB_APP_ENTERPRISE",
			"GIT_HUB_API",
			"ATOP",
			"SNYK",
			"STACK_HAWK",
			"BLACKFIRE",
			"BACKBLAZE",
			"ONE_LOGIN",
			"OKTA",
			"CONTENTFUL",
			"JIRA",
			"NPM_REGISTRY",
			"ANTHROPIC",
		])
		.optional(),
	auth_type: z
		.enum([
			"OAUTH",
			"TOKEN",
			"API_KEY",
			"APP",
			"APP_SPRYKER",
			"TOKEN_APP_EXTENSION",
			"DEFAULT",
			"OIDC",
			"TRUSTED",
			"APP_RW",
		])
		.optional(),
	scope: z.enum(["WORKSPACE", "PROJECT", "ENVIRONMENT"]).optional(),
	project_name: z.string().optional(),
	app_id: z.string().optional(),
	google_project: z.string().optional(),
	host_url: z.string().optional(),
	webhook_address: z.string().optional(),
	audience: z.string().optional(),
	atop_url: z.string().optional(),
	permissions: zIntegrationPermissionsView.optional(),
	all_pipelines_allowed: z.boolean().optional(),
	allowed_pipelines: z.array(zShortPipelineViewWritable).optional(),
	disabled: z.boolean().optional(),
});

export const zGetWorkspacesResponse = zWorkspacesView;

export const zGetWorkspacePath = z.object({
	workspace_domain: z.string(),
});

export const zGetWorkspaceResponse = zWorkspaceView;

export const zDisableSsoPath = z.object({
	workspace_domain: z.string(),
});

export const zEnableSsoPath = z.object({
	workspace_domain: z.string(),
});

export const zGetIdentifiersPath = z.object({
	workspace_domain: z.string(),
});

export const zGetIdentifiersQuery = z.object({
	project: z.string().optional(),
	pipeline: z.string().optional(),
	environment: z.string().optional(),
	artifact: z.string().optional(),
	artifact_version: z.string().optional(),
	sandbox: z.string().optional(),
	unit_test_suite: z.string().optional(),
	visual_test_suite: z.string().optional(),
	crawl_suite: z.string().optional(),
	distribution: z.string().optional(),
	route_subdomain: z.string().optional(),
	route_domain: z.string().optional(),
	route_path: z.string().optional(),
});

export const zGetIdentifiersResponse = zIdsView;

export const zDeleteIntegrationPath = z.object({
	workspace_domain: z.string(),
	hash_id: z.string(),
});

/**
 * Integration deleted successfully
 */
export const zDeleteIntegrationResponse = z.void();

export const zGetWorkspaceMembersPath = z.object({
	workspace_domain: z.string(),
});

export const zGetWorkspaceMembersQuery = z.object({
	page: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	per_page: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	sort_by: z.string().optional(),
	sort_direction: z.string().optional(),
});

export const zGetWorkspaceMembersResponse = zWorkspaceMembersView;

export const zAddWorkspaceMemberBody = zAddWorkspaceMemberRequest;

export const zAddWorkspaceMemberPath = z.object({
	workspace_domain: z.string(),
});

export const zAddWorkspaceMemberResponse = zWorkspaceMemberView;

export const zDeleteWorkspaceMemberPath = z.object({
	workspace_domain: z.string(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

/**
 * Workspace member deleted successfully
 */
export const zDeleteWorkspaceMemberResponse = z.void();

export const zGetWorkspaceMemberPath = z.object({
	workspace_domain: z.string(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

export const zGetWorkspaceMemberResponse = zWorkspaceMemberView;

export const zUpdateWorkspaceMemberBody = zUpdateWorkspaceMemberRequest;

export const zUpdateWorkspaceMemberPath = z.object({
	workspace_domain: z.string(),
	id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

export const zUpdateWorkspaceMemberResponse = zWorkspaceMemberView;

export const zGetWorkspaceMemberProjectsPath = z.object({
	workspace_domain: z.string(),
	user_id: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		}),
});

export const zGetWorkspaceMemberProjectsQuery = z.object({
	page: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	per_page: z
		.int()
		.min(-2147483648, {
			error: "Invalid value: Expected int32 to be >= -2147483648",
		})
		.max(2147483647, {
			error: "Invalid value: Expected int32 to be <= 2147483647",
		})
		.optional(),
	status: z.string().optional(),
	sort_by: z.string().optional(),
	sort_direction: z.string().optional(),
	all: z.string().optional(),
});

export const zGetWorkspaceMemberProjectsResponse = zProjectsView;

export const zGetSandboxesPath = z.object({
	workspace_domain: z.string(),
});

export const zGetSandboxesQuery = z.object({
	project_name: z.string(),
});

export const zGetSandboxesResponse = zSandboxesView;

export const zAddSandboxBody = z.union([
	zCloneSandboxRequest,
	zCreateFromSnapshotRequestWritable,
	zCreateNewSandboxRequestWritable,
]);

export const zAddSandboxPath = z.object({
	workspace_domain: z.string(),
});

export const zAddSandboxQuery = z.object({
	project_name: z.string(),
});

export const zAddSandboxResponse = zSandboxResponse;

export const zDeleteSandboxPath = z.object({
	workspace_domain: z.string(),
	id: z.string(),
});

/**
 * Sandbox deleted successfully
 */
export const zDeleteSandboxResponse = z.void();

export const zGetSandboxPath = z.object({
	workspace_domain: z.string(),
	id: z.string(),
});

export const zGetSandboxResponse = zSandboxResponse;

export const zUpdateSandboxBody = zUpdateSandboxRequestWritable;

export const zUpdateSandboxPath = z.object({
	workspace_domain: z.string(),
	id: z.string(),
});

export const zUpdateSandboxResponse = zSandboxResponse;

export const zGetSandboxAppLogsByIdPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	app_id: z.string(),
});

export const zGetSandboxAppLogsByIdQuery = z.object({
	cursor: z.string().optional(),
});

export const zGetSandboxAppLogsByIdResponse = zSandboxAppLogsView;

export const zStartSandboxAppPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	app_id: z.string(),
});

export const zStartSandboxAppResponse = zSandboxResponse;

export const zStopSandboxAppPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	app_id: z.string(),
});

export const zStopSandboxAppResponse = zSandboxResponse;

export const zGetSandboxCommandsPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zGetSandboxCommandsResponse = zSandboxCommandsView;

export const zExecuteSandboxCommandBody = zExecuteSandboxCommandRequest;

export const zExecuteSandboxCommandPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zExecuteSandboxCommandResponse = zSandboxCommandView;

export const zGetSandboxCommandPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	id: z.string(),
});

export const zGetSandboxCommandResponse = zSandboxCommandView;

export const zGetSandboxCommandLogsPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	command_id: z.string(),
});

export const zGetSandboxCommandLogsQuery = z.object({
	follow: z.boolean().optional(),
});

export const zGetSandboxCommandLogsResponse = zSandboxCommandLog;

export const zTerminateSandboxCommandPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	command_id: z.string(),
});

export const zTerminateSandboxCommandResponse = zSandboxCommandView;

export const zDeleteSandboxFilePath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	path: z.string().regex(/.*/),
});

/**
 * File or directory deleted successfully
 */
export const zDeleteSandboxFileResponse = z.void();

export const zGetSandboxContentPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	path: z.string().regex(/.*/),
});

/**
 * Content retrieved successfully
 */
export const zGetSandboxContentResponse = zSandboxContentView;

export const zCreateSandboxDirectoryPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	path: z.string().regex(/.*/),
});

/**
 * Directory created successfully
 */
export const zCreateSandboxDirectoryResponse = zSandboxContentItem;

/**
 * File to upload
 */
export const zUploadSandboxFileBody = z.string();

export const zUploadSandboxFilePath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	path: z.string().regex(/.*/),
});

/**
 * File uploaded successfully
 */
export const zUploadSandboxFileResponse = zSandboxContentItem;

export const zDownloadSandboxContentPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	path: z.string().regex(/.*/),
});

/**
 * File download
 */
export const zDownloadSandboxContentResponse = z.string();

export const zRestartSandboxPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zRestartSandboxResponse = zSandboxResponse;

export const zGetSandboxSnapshotsPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zGetSandboxSnapshotsResponse = zSnapshotsView;

export const zAddSandboxSnapshotBody = zAddSnapshotRequest;

export const zAddSandboxSnapshotPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zAddSandboxSnapshotResponse = zSnapshotView;

export const zDeleteSandboxSnapshotPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	id: z.string(),
});

/**
 * Sandbox snapshot deleted successfully
 */
export const zDeleteSandboxSnapshotResponse = z.void();

export const zGetSandboxSnapshotPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
	id: z.string(),
});

export const zGetSandboxSnapshotResponse = zSnapshotView;

export const zStartSandboxPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zStartSandboxResponse = zSandboxResponse;

export const zStopSandboxPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zStopSandboxResponse = zSandboxResponse;

export const zGetSandboxYamlPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zGetSandboxYamlResponse = zSandboxYamlView;

export const zUpdateSandboxByYamlBody = zSandboxYamlViewWritable;

export const zUpdateSandboxByYamlPath = z.object({
	workspace_domain: z.string(),
	sandbox_id: z.string(),
});

export const zUpdateSandboxByYamlResponse = zSandboxResponse;

export const zGetProjectSnapshotsPath = z.object({
	workspace_domain: z.string(),
});

export const zGetProjectSnapshotsQuery = z.object({
	project_name: z.string(),
});

export const zGetProjectSnapshotsResponse = zSnapshotsView;

export const zDeleteSnapshotPath = z.object({
	workspace_domain: z.string(),
	id: z.string(),
});

/**
 * Sandbox snapshot deleted successfully
 */
export const zDeleteSnapshotResponse = z.void();

export const zAddSandboxByYamlBody = zSandboxYamlViewWritable;

export const zAddSandboxByYamlPath = z.object({
	workspace_domain: z.string(),
});

export const zAddSandboxByYamlQuery = z.object({
	project_name: z.string(),
});

export const zAddSandboxByYamlResponse = zSandboxResponse;

export const zGetSsoPath = z.object({
	workspace_domain: z.string(),
});

export const zGetSsoResponse = zSsoView;

export const zUpdateSsoBody = zUpdateSsoRequest;

export const zUpdateSsoPath = z.object({
	workspace_domain: z.string(),
});

export const zUpdateSsoResponse = zSsoView;

export const zGetIntegrationsPath = z.object({
	workspace_domain: z.string(),
});

export const zGetIntegrationsResponse = zIntegrationsView;

export const zAddIntegrationBody = zAddIntegrationRequest;

export const zAddIntegrationPath = z.object({
	workspace_domain: z.string(),
});

export const zAddIntegrationResponse = zIntegrationView;

export const zGetIntegrationPath = z.object({
	workspace_domain: z.string(),
	hash_id: z.string(),
});

export const zGetIntegrationResponse = zIntegrationView;

export const zUpdateIntegrationBody = zUpdateIntegrationRequest;

export const zUpdateIntegrationPath = z.object({
	workspace_domain: z.string(),
	hash_id: z.string(),
});

export const zUpdateIntegrationResponse = zIntegrationView;
